rq/rq

.gitignore, requirements.txt, rq/cli/cli.py, rq/cli/helpers.py, rq/job.py, rq/queue.py, rq/suspension.py, rq/utils.py, rq/worker.py, tests/test_cli.py, tests/test_queue.py, tests/test_worker.py
**Problem Statement**
We use rq on heroku and their way to the shutdown the worker that runs rq does not ensure a safe shutdown.
From Heroku docs:  https://devcenter.heroku.com/articles/dynos
```
When a worker is stoped by ps:scaling or pushing out a new release or any heroku operation.
The dyno manager sends the working SIGTERM
The process then has 10 seconds to shut down gracefully.
If the process is still alive -- then SIGKILL is then sent
```
So if a job takes more then 10 secs (which many of our jobs do) -- we are going to be out of luck.  The job will be killed in a potentially unsafe point
So we needed an approach where we could set a flag on redis, that the rq worker can ping.
I introduced the key:  'rq:worker:pause_work'  Which any process can set.  If the worker sees that it has …
=> triggering shutdown by setting a redis flag

rq/queue.py, tests/test_queue.py
You could view this as an alternative (and less-code) implementation of #452:
I ran into a situation where it would be very advantageous to queue a specific job *now* (instead of the end of the queue). So I implemented a `skip_queue` option the the various `Queue.enqueue` methods, which does an lpush instead of an rpush.
To accomplish #452 with this you'd enqueue each job specifying `skip_queue=True`. A better way to do this might be changing the default for `skip_queue` from `False` to `None`, and having the lowest level method here (`Queue.push_job_id()`) pull a default from the `Queue` (which we could set at initialization, default `False`). If this is desired renaming the argument from `skip_queue` to something more like `fifo` would likely be a good idea.
If the maintainers think …
=> Skip queue

rq/worker.py
Worker should wait until horse process finishes.
Current implementation ends up raising a StopRequested exception, therefore stopping the parent process without waiting for the horse process to finish. 
python run_worker.py
11:07:33 RQ worker started, version 0.4.6
11:07:33
11:07:33 *** Listening on default...
11:07:33 default: fib.slow_fib(1) (9a94e99a-adbe-430a-a0ab-4656afd477ba)
^C11:07:34 Warm shut down requested.
Traceback (most recent call last):
File "run_worker.py", line 11, in <module>
Worker(q).work()
File "/Users/javier.lopez/Dev/rq_test/src/rq/rq/worker.py", line 367, in work
self.execute_job(job)
File "/Users/javier.lopez/Dev/rq_test/src/rq/rq/worker.py", line 438, in execute_job
os.waitpid(child_pid, 0)
File "/Users/javier.lopez/Dev/rq_test/src/rq/rq/worker.py", line 331, in …
=> Make parent worker process wait until horse process finishes

rq/job.py, rq/queue.py, rq/registry.py, rq/worker.py, tests/test_job.py, tests/test_queue.py, tests/test_registry.py
This pull request introduces a new job status: `DEFERRED`. Jobs that have not been queued due to unmet dependencies are now assigned this status. Deferred Jobs are also put in a `DeferredJobsRegistry` so we can keep track of jobs that will be queued when their dependencies are met.
I plan on merging this into master in a week, @nvie please let me know if there's any feedback.
=> Deferred job status

rq/job.py, tests/test_job.py
get_call_string() failed if any arguments contained non-ASCII strings.
Fixes #406
=> Allow non-ASCII characters in arguments

rq/queue.py
`watch` command should be used in conjunction with `multi` command
which was missed in enqueuing of job with dependencies.
I'm not sure about why `DEFERRED` status is set via different connection (not the current pipe). 
Fix #487
=> Add missed `multi` command after `watch`

rq/worker.py, tests/test_worker.py
As discussed a LONG time ago in https://github.com/nvie/rq/pull/252
Add birth and death properties to Worker
=> add birth_date and death_date properties to Worker

rq/cli/helpers.py
Allow the worker to connect to a Redis instance through SSL (ex: Azure
Redis Cache use SSL only by default)
The following option is added to the worker optional config file: 
REDIS_SSL = True
=> Add REDIS_SSL option in worker config file

.travis.yml, rq/queue.py, tests/test_queue.py
In the case of many sequential jobs having been deleted, a recursive
implementation of `Queue#dequeue` is prone to blowing the stack in the
absence of tail-recursion support. Change the implementation from
recursive to iterative to work around this issue in CPython.
=> Prevent `Queue#dequeue` from blowing the stack

rq/worker.py
- Include worker key in worker startup log statement.
- Added a notification to make it more clear when a 'burst' worker dies.
```
rqworker --burst  
17:24:34 RQ worker, 'rq:worker:Trevors-MBP.26302', started, version 0.5.1
17:24:34 
17:24:34 *** Listening on default...
17:24:34 RQ worker, 'rq:worker:Trevors-MBP.26302', has died.
```
=> Improving logging.

rq/job.py
This is related to #492 (Allow non-ASCII characters in keyword arguments), it's followup #510 (change try/except in python2/3 compatibility to to_text()) and #406 (Handle Unicode in Job args & kwargs).
The patched `Job.get_call_string()` in #510 doesn't incorporate the use of `as_text` for allowing Unicode in kwargs, only for args. Under python 2.7 I was getting a UnicodeDecodeError ('ascii' codec can't decode byte) when a kwargs value contained a non-ASCII unicode character (é, or 0xc3 in this case).
Patching the formatting of the kwargs list using `as_text` in the same way as the args list, as in this PR, fixed the problem (note, I'm only patching the kwarg value here, not the kwarg key, which could in principle also have non-ASCII unicode characters).
There isn't an update to the …
=> Allow non-ASCII characters in keyword arguments.

rq/registry.py, rq/worker.py, tests/test_registry.py, tests/test_worker.py
Version 0.5.0 introduced `StartedJobRegistry` and `FinishedJobRegistry`. Unmaintained, job registries could grow to really large sizes. This is reported by @cosminstefanxp in #519 .
This PR introduces a feature where workers will clean up job registries every hour without having to run out of band maintenance scripts, simplifying worker deployments.
If there's no complaints, I'll merge this in a few days.
Fixes #519.
=> Worker automatically cleans job registries every hour

tests/fixtures.py, tests/test_job.py
Added test coverage for unicode keyword argument support in method signatures (#536). Confirmed that this fails pre-536, and passes post-536.
=> Added test coverage for unicode keyword argument support

rq/job.py, tests/test_job.py
Fixes some broken tests and misbehaviour with ttls. There was a temporal
coupling between saving the job and setting its expires parameter.
=> Fixes #502

rq/queue.py, tests/test_job.py, tests/test_queue.py
Current implementation is using the first job queue to insert all dependent jobs, ignoring the queue where the jobs were enqueued.
With this change, we will use job origin attribute to fetch the original queue, then insert the dependent job to the fetched queue.
fixes issue #512
=> support multiple queues on dependent jobs

rq/worker.py
I think it makes sense moving output to DEBUG as you'd care about it in logs only while debugging. Over certain size the output in logs also gets quite unwieldy, so truncating it to 2k chars.
Keep up the good work and let me know if things should be done differently!
=> log job result in DEBUG level and truncate to 2k symbols

.travis.yml, rq/worker.py, run_tests, tests/__init__.py, tests/test_worker.py
ref #584, this doesn't fix that problem but it should make implementing a better Heroku worker easier, I think it should also improve coverage since `_install_signal_handlers`, `request_force_stop` and `request_stop` are currently not tested at all.
=> Signal changes

rq/worker.py
Changed to mirror the [job started](https://github.com/nvie/rq/blob/master/rq/worker.py#L461-L462) log entry.
The current simple "Job OK" message is pretty useless if you have multiple queues executing jobs, it can take ages work out which job was ok and it's impossible if you have multiple workers running and can't differentiate between their logs.
=> more info in 'Job OK' log entry

rq/worker.py
Set the worker to busy before forking the horse. Right now only the fork is set to busy and SIGINT will kill the worker without waiting for the horse to finish.
=> mark as busy before forking horse

patterns/index.md
Heroku Example:
When importing the redis connection instance from another file,
the worker is run immediately, blocking the execution of the rest of
the code.
This fixes the worker to only be run only if the worker is executed from
the command line and not when imported.
[Sample Use Case](https://devcenter.heroku.com/articles/python-rq)
=> [Docs] Prevent running worker when the connection instance is imported

rq/cli/cli.py
I had a problem with the rqinfo command, because I keep the rq in the 1st database instead of 0.
And because of this the rqinfo command can't show me any  information.
This patch is allows me to use config to get the rq informations from the 1st db.
=> rqinfo config parameter

rq/worker.py
This was initially spurred by #479. Idea behind doing this:
+ including worker id and job id in logs and relevant HTTP request headers
+ no additional redis connection or request required
+ no API change: workers can look for env vars and use them if found
Environment variables can be abused much as global variables often are, but they feel like a good fit here for communicating contextual read-only information from the parent worker to the child work horse process.
=> export worker id and job id as env vars to work horse

rq/job.py, rq/worker.py, tests/test_job.py, tests/test_worker.py
currently only `enqueued_at` and `ended_at` are available which means it's not possible to calculate either how long the job was in the queue for or how long it took to be performed. Adding the time the job was started at means both these numbers can be calculated.
=> add job.started_at

requirements.txt, rq/compat/connections.py
This has been discussed in #514, #282 and #88.
Using an explicit type check via `isinstance`, rather than duck typing, is typically considered unpythonic and breaks compatibility with mock objects such as FakeRedis. This patches removes the type check, and instead looks for a common method that should be present on the object as a hint on whether it's compatible or not.
=> Fixes #613

rq/job.py, rq/queue.py, tests/test_queue.py
Makes it very easy to add meta data to a Job in the Queue.enqueue call. Currently you would have to create the Job separately, set its metadata and then call enqueue_job. This way you only need to provide the 'meta' keyword arg to the enqueue call and you're set.
This was mentioned in issue #528 too.
Let me know what you think.
Thanks
-Tim
=> Allow meta when enqueing

rq/cli/cli.py
The `--results-ttl` value isn't currently being cast as an integer when passed from the command line, this causes issues further down when a value is sent as it remains a string i.e:
```
..../site-packages/rq/registry.py", line 32, in add
score = ttl if ttl < 0 else current_timestamp() + ttl
TypeError: unorderable types: str() < int()
```
Fixed to cast value as integer.
=> Correction to results-ttl value on worker command

rq/queue.py, tests/test_job.py
When you're working in not `async` mode (usually when debugging) and you're checking if the job is finished, never is finished because the `worker` sets the `FINISHED` status.
With this patch the job is marked as finished when working in async mode.
=> When not async set job finished

docs/monitoring.md, docs/workers.md, index.md, patterns/django.md, patterns/supervisor.md
It is confusing to newbie like me whether to use `rqworker` or `rq worker`. According to [the source code](https://github.com/nvie/rq/blob/0.5.6/setup.py#L48-L49), use of `rq worker` seems to be recommended rather than `rqworker`. So this pull request replaces all the `rqworker` and `rqinfo` with `rq worker` and `rq info` in the documentation.
=> docs: Use rq command instead of rqworker/rqinfo

rq/worker.py, tests/test_worker.py
Currently, passing byte strings to the first argument of `Worker()` will cause `TypeError: xxx is not of type <class 'rq.queue.Queue'> or text type`.
However, I think passing byte strings is natural in Python 2. In addition, accepting byte strings make it easy to write Python 2/3 compatible code.
e.g.
```py
Worker(sys.argv[1:])
Worker(['high', 'normal', 'low'])
```
This PR accept these forms both in Python 2 and 3.
=> Accept byte strings as the first argument of Worker() in Python 2

docs/workers.md
The following worker script in [the worker document](http://python-rq.org/docs/workers/) does not work well in Python 3.
```py
#!/usr/bin/env python
import sys
from rq import Queue, Connection, Worker
import library_that_you_want_preloaded
with Connection():
qs = map(Queue, sys.argv[1:]) or [Queue()]
w = Worker(qs)
w.work()
```
Running `python3 myworker.py` will cause `redis.exceptions.ResponseError: wrong number of arguments for 'blpop' command`. This is because `map(Queue, [])` in Python 3 returns an iterator which is evaluated as `True`.
Just passing the list of strings to `Worker()` should fix the problem.
```py
qs = sys.argv[1:] or ['default']
```
This also simplify the worker script.
NOTE: the modified script depends on #650. Without it, the worker script does not work in Python 2.
=> docs: Make sample code of workers compatible with Python 3

rq/cli/cli.py, rq/worker.py, tests/test_worker.py
Otherwise I had to do something like:
```python
worker = Worker(queues)
worker.queue_class = CustomQueueClass
worker.work()
```
With this pull request, it's now possible to do:
```python
worker = Worker(queues, queue_class=CustomQueueClass)
worker.work()
```
Also, before this pull request, passing the queue class in the command line would not work as expected.
=> Worker accepts custom queue class

rq/decorators.py, tests/test_decorator.py
Add a ttl argument to decorator which will set a TTL for the job.
Default value is None.
=> Add ttl argument to decorator

rq/logutils.py
I am running worker on a separate process starting from my app using `multiprocessing`. My application configures the logs, but the worker class also wants to do it (actually, it just adds one handler). The effect is that logs from worker are doubled and don't go to the stream I want.
I hope that I understood the original intention behind this code.
=> Worker only creates log handlers if there aren't any.

rq/logutils.py
logger.setLevel() doesn't work when a string is passed in Python-2.6.
This patch checks if the level has been set and if not (in Python-2.6),
tries to set it again using appropriate level constants
Also unused dictConfig import is removed
=> Fix logging regression for Python-2.6

setup.cfg, tests/test_queue.py, tests/test_worker.py, tox.ini
Sadly the flake8 isn't run in travis (and I don't change that here). But it should still be made green. And the config should be placed in setup.cfg so editors can use the same config for flake8 as tox does.
=> Ignore lambdas in flake8

rq/worker.py
this is the little change that has the worker use the passed-in connection if provided. This works on my development systems, but have not created any additional test cases :(
=> have worker use the passed-in connection if provided

rq/logutils.py, rq/worker.py
This is just a patch to expose the logging level on the Worker.work() method.
For instance, it will allow to mute all RQ output if you're using the RQ Worker class.
=> Allow Worker work method to specify the log verbosity

rq/job.py, rq/worker.py, tests/test_worker.py
This issue #600 migrate `job.cancel()` to `job.delete()` .
When enqueue a job with `result_ttl=0`, after this job is executed, `job_status` is not updated and the `job.cleanup(result_ttl, pipeline=pipeline)` will be called immediately. In `job.cleanup`, `job.cancel()` will be called to remove itself from its `origin queue`, however the job object has already been poped from the `origin queue`.
A redis `lrem ` is used in  `job.cancel()`, this command is O(N) in time complexity and will be very slow if have millions of jobs in the queue. What's more calling `job.cancel()` with a finished job is meaningless.
=> Don't call job.cancel if job has finished

rq/job.py, tests/test_job.py
This patch includes a fix and a simple test for the cancel_job helper function that was not working as expected.
fixes issue #700
=> Fixes issue #700

rq/job.py, tests/test_job.py
The cancel method was not working correctly for the special failed queue.
=> Fix Job.cancel() method on failed queue

.travis.yml, rq/worker.py, tests/fixtures.py, tests/test_job.py, tests/test_queue.py, tests/test_worker.py, tox.ini
When running the stock worker itself, the `_connection_stack` is empty. Sadly this only shows when the `rqworker` runs in its own python process. The existing tests in test_worker.py and test_cli.py don't do that.
This branch adds tests that run the stock worker in its own subprocess, thus showing the problem. And it extends the cli to push (and pop) the redis connection when running the worker.
Also I changed the existing `access_self` function to also assert on `get_current_connection`. And this extends the existing worker test to check the failed queue to see that no job failed.
This fixes #479.
=> Fix connection stack in stock worker

rq/worker.py
There was a comment asking if there's a better way to do signal name lookups than what was there. There is in Python3.5, so I added it!
=> Added better signal name lookup

.travis.yml, rq/worker.py, tests/test_worker.py
In order to solve issue 702 we have to check whether a work-horse terminated unexpectedly (by inspecting the exit code of the work-horse process). If it exited unexpectedly we check if the job has either been marked as finished, failed or other valid states. If it's not in any valid state we mark it as failed and move it to the failed queue. Since the process was terminated unexpectedly (think OOM) we do not have any exception context and we can't run any custom exception handlers.
There is still a chance that the job will finish successfully but the work-horse process will be killed before the job is marked as finished and we will erroneously mark it as failed. The users should take care to write idempotent jobs.
=> Fix issue 702

rq/worker.py
The signal handler request_force_stop_sigrtmin (introduced with the heroku specific worker) would fail in python3 because it was trying to read frame properties that have been removed in python3.
We now handle python2 as a special case with more frame properties.
Also fixed some warnings about using the war function of the logger
=> Fix request_force_stop_sigrtmin failing for python3

rq/worker.py, tests/fixtures.py, tests/test_worker.py
Uses compat for PY2 check and add tests which check the error raised by signals is correct.
Fixes #715, improves #727
=> Improved fix for python 3 frame handling and tests

rq/cli/cli.py, rq/cli/helpers.py
=> custom connection class

rq/exceptions.py, rq/queue.py, tests/test_queue.py
Adapted some tests to the change: the dependency has to be saved first.
This is a replacement for the PR #743 (see https://github.com/nvie/rq/pull/743#issuecomment-241607859).
=> Raise an exception if a given dependency does not exist

tests/test_worker.py
=> Stop running some Heroku tests on macOS since it’s missing the appropriate signals

rq/queue.py, tests/test_queue.py
#733 broke getting job on the failed queue, making it impossible to display detail in rq-dashboard or django-rq, this PR add another check on the requesting queue.
=> Fix get job on failed queue

rq/queue.py
Not sure if this is correct, but I was looking through the code and noticed that if a pipeline is passed to `Queue.cancel` we add an `lrem` call to the pipeline and then also call `lrem` immediately on the connection.  I think we just want to add it to the pipeline in that case?
=> Don't run lrem directly if we have a pipeline

rq/cli/cli.py
Related to nvie/rq#777
AFAIK, nobody would like to use the default async transport as it won't work. Maybe we can add a parameter `--sentry-transport-class`.
(and thanks for rq!)
=> fix: set HTTP transport as default for sentry

rq/worker.py, tests/test_worker.py
I sometimes wonder if I'm the only person who actually bothers to writing unit tests for code that uses rq in `async` mode.
This fix prevents the heroku worker hanging indefinitely on termination of the process when the horse is already down. I guess my fault when I first submitted the heroku worker.
Further tests should not be required as the logic in `kill_horse` is taken from `request_force_stop` where is was previously tested.
=> allow for already dead horse on heroku worker termination

rq/job.py, rq/queue.py, rq/registry.py, rq/worker.py, tests/fixtures.py, tests/test_worker.py
* Prevents clobbering of user-supplied metadata
modified during the job execution
* Allows the "Storing arbitrary data on jobs" example at http://python-rq.org/docs/jobs/ to actually persist.
=> Trigger a refresh after job execution

rq/cli/cli.py
The Threaded transport (default) is not reliable, breaking the error reporting. This PR switch it to the HTTPTransport bringing a working out-of-the-box experience.
I can also add a `--sentry-transport-class` option to the CLI if you want/prefer.
=> Use HTTPTransport transport so sentry reporting works by default

README.md
The pip install -e directions don't work for users without write access to the repo. This documentation fixes that problem.
=> Fix pip install from HEAD of origin/master

docs/exceptions.md
It should be 'w' instead of 'worker' for the name of worker object.
=> Typo in sample code

rq/worker.py
Minor spelling update of `proccess` to `process`
=> Minor spelling mistake

rq/queue.py, tests/test_job.py
Currently, the job is being performed inside `enqueue_call()`, which
means that `async=False` has no effect if `enqueue_job()` is called
directly. This commit fixes that.
=> Make `Queue.enqueue_job()` execute job immediately if `async=False`

rq/exceptions.py, rq/queue.py, rq/utils.py, tests/test_utils.py
Support specifying timeout values using strings instead of ints.
Timeout can be: 1, '1s', '1S', '1m' ,'1M', '1h', '1H'.
=> Fixed issue#72

rq/worker.py
I got this stack trace during a warm shutdown:
```
StopRequested: null
File "rq/cli/cli.py", line 206, in worker
w.work(burst=burst)
File "rq/worker.py", line 461, in work
self.heartbeat()
File "rq/worker.py", line 510, in heartbeat
connection.expire(self.key, timeout)
File "redis/client.py", line 865, in expire
return self.execute_command('EXPIRE', name, time)
File "redis/client.py", line 573, in execute_command
return self.parse_response(connection, command_name, **options)
File "redis/client.py", line 585, in parse_response
response = connection.read_response()
File "redis/connection.py", line 577, in read_response
response = self._parser.read_response()
File "redis/connection.py", line 238, in read_response
response = self._buffer.readline()
File "redis/connection.py", line 168, in …
```
=> fix uncaught StopRequested during send heartbeat

rq/handlers.py, rq/worker.py
Fixed issue #711 
* Separate move_to_failed_queue from the worker to allow it's use in cli exception handler.
=> Expose move_to_failed_queue from Worker

rq/job.py, rq/queue.py, rq/registry.py, tests/test_job.py, tests/test_queue.py
As discussed [here](https://github.com/nvie/rq/pull/825#discussion_r114075946)
=> Replace job id with job instance in the job stack. Remove implicit "cleanup" call from "job.save"

rq/worker.py
The `signal.SIGKILL`-constant is not available on the windows platform. Like in werkzeug (https://github.com/pallets/werkzeug/commit/68e1ba06500914089723a3744a5ab93aa212b3a3) using `signal.SIGTERM` should fix the problem.
=> Windows: Use SIGTERM instead of SIGKILL

.travis.yml, py26-requirements.txt, rq/logutils.py, setup.py, tests/test_worker.py
as per discussion #715 this removes python 2.6 support.
There are probably (definitely) lots of improvements possible now the syntax doesn't have to be stretched to support such a massive range of python versions, but this is a start.
**Rationale**: I was thinking about submitting a PR for #721 as someone suggested and realised that the reason I was unkeen was having to remember how an outdated version of python worked and maybe hack around to get python 2.6 installed to test the code. Removing this should make contributing to rq much easier for everyone.
Anyone still running 2.6 has much bigger problems than upgrading rq: they need to concentrate on upgrading to 2.7 and then 3 or scrapping their code-base and starting again.
=> remove python 2.6 support

tests/dummy_settings_override.py, tests/test_cli.py
Tests show that the config parameters from a file do get passed in the Redis connection pool
=> Fixed #809 - Added tests for various cli config parameters

rq/worker.py
Hi!
Recently we've had the issue, that an exception contained binary data in its message, which could not be decoded as utf-8. This PR uses latin-1 to decode the exception strings if utf-8 decoding fails.
Thanks for considering!
=> try latin-1 if utf-8 doesn't work, when decoding exception strings

rq/worker.py, tests/test_worker.py
Fixed an issue where worker.refresh() may fail if `birth` is not present in Redis.
=> Fixed an issue where `birth` not present in Redis

rq/worker.py, tests/test_worker.py
Worker logging is currently pretty verbose and naively configured. 
This improves it.
Changes:
* logging `*** Listening on ...` before/after every job moved from INFO to DEBUG
* logging `*** Listening on ...` at INFO on initial load.
* `log_result_lifespan` to prevent, `Result is kept for 500 seconds` being logged for every job
* whoever initially implemented logging in `worker` apparently didn't take the time to look at how python logging works - it specifically allows `log.info('template with var %s', var)` syntax to avoid formatting log statements which are subsequently dropped. I've fixed this on all `DEBUG` log statements, as that will have the most effect since they're generally dropped.
* there was a bunch of white space at the end of lines (is rq not running linting !?) which …
=> improve logging in worker.py

rq/decorators.py
After using `@job` decorator for a function that takes a long string, in RQ worker I got printed all the args/kwargs via `job.get_call_string()`.
To get this overridden, I added `description` argument to the decorator.
I decided not to put this in `delay` method because it's may be currently be used by end user.
=> Add description param to  @job decorator

dev-requirements.txt
PyTest is required for running tests, but was not present in dev-requirements.txt
=> Added pytest to dev-dependencies

rq/job.py, tests/test_job.py
Linked to PRs https://github.com/rq/rq/pull/427 and https://github.com/rq/rq/pull/856
As discussed in both of the above PRs I am introducing a method to explicitly delete dependents of a job.
In this implementation deleting a job by default does not touch the dependents (should we introduce a CANCELED or ORPHANED state?).
In case a user uses `delete_dependents=True`, all dependent jobs are deleted.
Since canceling a job only removes it form the queue and dependents are not in a queue yet anyway that method is not involved.
=> Delete dependents of job explicitely

index.md
Changed Redis version requirement to be the same as one specified by Readme.
https://github.com/rooterkyberian/rq/commit/c6f79784640f95635b5e575e6691caa47350e948
=> update Redis requirement to one specified by readme

rq/job.py, rq/queue.py, tests/test_job.py
Some prefixes were hardcoded in several places. This made it hard to
use custom prefixes via subclasses.
Resolves #920
=> Define redis key prefix as class variable

docs/docs/index.md
You can use WSL and run RQ and Redis on Windows by running them in a bash shell within windows.
=> Windows Clarification

.travis.yml, docs/docs/index.md, docs/docs/testing.md, rq/queue.py, setup.py, tests/test_job.py, tests/test_queue.py, tox.ini
This PR provides Python 3.7 compatibility by changing the Queue object's `async` keyword to `is_async`. For backwards compatibility, `**kwargs` is checked for the `async` keyword and will continue to work, but will raise a warning.
All tests and documentation references are updated to use `is_async` instead of `async`.
Some other PR's are suggesting reversing the keyword (i.e. `sync`) which will break any code that uses ordered keywords rather than named keywords, so this PR is intended to provide a safer alternative.
=> Replace 'async' keyword with 'is_async' for Queue objects

docs/docs/index.md, docs/docs/jobs.md
I was working my way through the documentation and had to change a few print statements to print functions for the examples to run in Python 3.
As most new projects begin with Python 3, I thought it would be a good idea to update the examples in the documentation.
Please let me know if I missed anything. Thanks!
=> Update docs to use print function vs print statement

rq/queue.py, tests/test_queue.py
When creating a queue we are allowed to specify if its async or not, but there is no way to know if a current queue instance is async or not without knowing the internals of the code.
This just exposes that setting as a property on the queue.
=> add is_async property to queue

docs/docs/workers.md, rq/timeouts.py, rq/worker.py
This allows custom workers to use associated custom `DeathPenalty` classes and apply custom timeouts or less messy death methods.
Implemented with **kwargs so future changes to `BaseDeathPenalty` wont break API.
=> Pass job_id to death penalty class

.travis.yml, setup.py
Redis >= 3.X does only support Python >=3.4.
=> Remove Python 3.3 support.

rq/utils.py
Prepare for 3.8 when it is deprecated.
=> Fix collections abc import deprecation warning.

docs/docs/jobs.md
=> Variable name mismatch

docs/docs/jobs.md
Job objects no longer have `.status` attribute - correct docs to use the `.get_status()` function.
=> Fix docs on job attributes

docs/docs/index.md
queue.enqueue() has arg `f`, not `func` (like enqueue_call).
=> Fix usage example of queue.enqueue()

rq/worker.py, tests/test_worker.py
See issue #1085 
Fixed by adding a check for negative `job.timeout` value before adding the job to the `StartedJobRegistry`.
=> Fix timeout adding job to StartedJobRegistry

.travis.yml
py3.7 has been out for a bit. It makes sense to have the tests start checking out if 3.8 will work.
=> CI - test against py3.8

rq/cli/cli.py
PR #991 introduced this useful flag but it seems to have missed
passing this flag to the worker. This simple commit fixes that
issue.
=> Fixes disable-job-desc-logging flag on CLI

CHANGES.md, docs/docs/workers.md, rq/cli/cli.py, rq/worker.py, tests/test_worker.py
This adds the ability to the worker to gracefully exit after a maximum number of jobs have been processed. The behaviour is similar to `--burst` except instead of processing until all queues are empty, it will exit after the limit is reached.
This will be useful in situations where the queue is known to be busy for a long time and you want to stop part way through, push our a deploy of your application, and then have the worker start up again with the updated job code.
Let me know if you would prefer different naming or coding conventions.
=> add the ability to have the worker stop executing after a max amount of jobs

rq/decorators.py, tests/test_decorator.py
Without it you cannot specify custom timeout for failed jobs created using decorator
=> Add failure_ttl on job decorator

docs/docs/jobs.md
Fixes a minor typo in the documentation for jobs.
Thanks for creating and maintaining `rq`!
=> docs/jobs: Fix minor typo

tests/test_worker.py
Also make error message more useful in case of future failures.
Stumbled upon this during preparation of previous PR, but was unable to reproduce It. Adjusted limits a little bit.
=> Fix unreliable test

docs/_config.yml, docs/docs/job_registries.md
Adds a page documenting the types of job registries. I did debate whether to insert this on an existing page such as the Queues page. The Queues page has gotten fairly large, though. Let me know, @selwin, if you have a preference.
=> add doc page for job registries

rq/worker.py, tests/test_worker.py
Mostly for displaying purposes (in RQ dashboard).
Also allows to detect partial upgrades when some workers are running old RQ/Python version.
=> Store worker's RQ and Python versions

rq/queue.py
If Queue was subclassed and enqueue_job changed, these changes should affect on dependent jobs' enqueueing too.
```
class MyQueue(Queue):
def enqueue_job(self, *args, **kwargs):
logger.info('Job was enqueued')
return super().enqueue_job(*args, **kwargs)
```
=> Fix dependent jobs enqueueing

rq/job.py, rq/queue.py, tests/test_job.py, tests/test_queue.py
Internal API changes to support multiple dependencies.
Successor to  #1147.
* Store all of a job's _dependencies_ in a redis set. Delete that set when a job is deleted.
* Add `Job#fetch_dependencies` method - which return all jobs a job is dependent upon and optionally _WATCHES_ all dependency ids.
* Use `Job#fetch_dependencies` in `Queue#call_enqueue`. `fetch_dependencies` now sets WATCH and raises `InvalidJobDependency`, rather than `call_enqueue`.
`Queue` and `Job` public APIs still expect single ids of jobs for `depends_on` but internally register them in a way that could support multiple jobs being passed as dependencies.
Next up: updates to `Queue#enqueue_dependents`.
=> Multi Dependency Support - Registration & Enqueue Call

rq/cli/cli.py
When using both parameter, like this:
```
> rq worker -v --logging_level="INFO"
```
`-v` override `--logging_level`
=> fix log level parameter override, Fixes #1166

docs/docs/workers.md
Fix #1152 by adding in an example for connecting to unix sockets from the command line
=> Add example for unix://

rq/logutils.py, rq/scheduler.py
The current way the logger is configured in the scheduler impacts other loggers in our project. This probably relates to https://github.com/rq/rq/issues/1177 too.
This PR uses RQ's `setup_loghandlers` instead of calling `logging.basicConfig` directly.
=> fix: use correct logging handler for scheduler

rq/worker.py
This PR alters the hard kill performed in the worker on heartbeat: timeout values of `-1` are considered "no timeout" or "infinite timeout", and no hard kill is performed.
Fixes #1186
=> Respect timeout -1 in worker hard kill

rq/cli/__main__.py
This PR adds a `__main__` file, such that the RQ CLI can be launched with `python -m rq.cli`.
Currently the `setup.py` console scripts declaration causes a similar file to be generated for the `rq` script:
```python
import re
import sys
from rq.cli import main
if __name__ == '__main__':
sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
sys.exit(main())
```
However, that's not available where I want it to be.
=> Add rq.cli.__main__

rq/worker.py
The worker handles exceptions in the job outside of the job's own context, so an exception handler / logger cannot call `get_current_job()` to obtain the job ID. The job ID can be used to locate the job in the failed job registry, which allows useful behaviors such as linking to a failed job on a dashboard in an error report.
Closes #1192.
=> Pass job ID to error handlers

rq/worker.py, tests/test_worker.py
after #1194
fix #1212
@selwin in future I would suggest you get tests to pass before merging PRs rather than merging them with failing tests, then asking someone else to resolve the broken tests.
I'm not at all clear why `p.exitcode is None` even though the processes seems to have been successfully killed, so this is the best I can do.
=> fixing HerokuWorkerShutdownTestCase

.travis.yml, dev-requirements.txt, docs/docs/jobs.md, docs/docs/workers.md, rq/exceptions.py, rq/job.py, rq/queue.py, rq/serializers.py, rq/worker.py, tests/fixtures.py, tests/test_job.py, tests/test_queue.py, tests/test_serializers.py, tests/test_worker.py
Based of inspiration gotten from https://github.com/rq/rq/pull/1141
This is an approach to create Queues and Jobs with customized serializer objects.
The serializer object should have at least dumps and loads methods.
If no serializer is specified, it defaults to pickle
Usage:
```
import dill
import json, pickle
job = Job(connection=connection, serializer=dill)
queue = Queue(connection=connection, serializer=dill)
queue = Queue(connection=connection, serializer=pickle)  # pickle serializer
queue = Queue(connection=connection, serializer=json)
```
Closes issue https://github.com/rq/rq/issues/369
I'd appreciate any and all feedback on this approach!
=> Implement Customizable Serializer Support

rq/logutils.py, rq/worker.py
Hello,
This pull request contains 2 small changes to allow passing lowercase logging levels:
```shell
rq worker --logging_level debug
```
Now `logutils.setup_loghandlers` accepts both lowercase and uppercase logging level names and numeric values, for example when setting the level from the `logging` module constants (e.g. `logging.DEBUG`).
The second change allows passing the `exception_handlers` of the `Worker` class as a `list` or a `tuple`.
```python
from rq import Worker
import handlers
w = Worker(exception_handlers=(handlers.one, handlers.two))
```
=> Accept lowercase logging level names and accept tuples when setting exception handlers

rq/queue.py
Hello,
This pull request adds the queue to the Redis queues set when a job is scheduled, previously if you schedule a job on a queue that doesn't have any jobs then the job will be added to the `ScheduledJobRegistry` but the queue won't be available in the queues set:
```console
127.0.0.1:6379> keys *
1) "rq:scheduled:default"
2) "rq:job:52c77ae6-e85c-43c6-9649-38f293be5bcb"
```
So when getting all the queues using `Queue.all()` we won't get this queue in the list because it wasn't added, so now when scheduling a job the queue will be added to the set in the `Queue.enqueue_at` method which is also used by `Queue.enqueue_in` matching the behavior of the `Queue.enqueue_job` method which adds the queue:
```python
pipe.sadd(self.redis_queues_keys, self.key)
```
This is useful for monitoring …
=> Add the queue to the Redis queues set when scheduling a job

rq/worker.py
Solves #1241 where `monitor_work_horse` could have a stale reference to `job.started_at` if the job is being reused by a scheduler (like rq-scheduler).
=> Always set job.started_at in monitor_work_horse

docs/docs/scheduling.md
Small typo.
Also, you may want to delete the `gh-pages` branch since you have switched to the `/docs` source for your GitHub Pages. (I tried to fix the typo in that branch first)
=> Fix typo in scheduling doc

rq/decorators.py
Closes #1236 by popping `job_id` from keyword arguments given to a decorated job function's `delay()` method and passing it to `enqueue_call()`.
=> Parse job_id as keyword argument to delay() (#1236)

rq/worker.py
This addresses issue #1246.
The exception handling block was raising the caught exception in-place, which caused the original traceback info to be lost. Rather than replace `raise e` with `raise`, I simply removed the whole try / except, since no action was being taken in the except block.
=> Remove extraneous try/except

rq/compat/__init__.py, rq/job.py, rq/worker.py
Re: https://github.com/rq/rq/issues/1244, this PR adds an `hmset` function to the compatibility module such that `hset` is preferred over `hmset` when running `redis-py` 3.5.0+.
=> Avoid deprecation warnings on redis-py 3.5.0 hmset

rq/serializers.py, tests/test_serializers.py
Re: https://github.com/rq/rq/issues/1252, this PR sets the default serializer to use `pickle.HIGHEST_PROTOCOL`, to match with the versions before 1.4.0.
Use can provide a class similar to `DefaultSerializer` to use a different protocol version.
=> Use pickle.HIGHEST_PROTOCOL by default

rq/job.py, rq/queue.py, rq/worker.py, tests/test_job.py, tests/test_queue.py
successor to #1155 
This PR updates `Queue#enqueue_dependents` such that only those _dependents_ for which all _dependencies_ are complete, will be enqueued. It includes:
- New method on `Job#get_dependencies_statuses` to retrieve the status of all of a jobs _dependencies_.
- A modification to `Queue#enqueue_dependents` (as described above).
- A modification to `Worker#handle_job_success` so that the status of **ALL** successful jobs is persisted to `FINISHED` in Redis.
- A small fix(?) to `Job#set_status` so that it uses a pipeline when appropriate.
Notwithstanding any bugs, I believe the next step here is to modify `Job` such that it accepts more than one dependency(in `depends_on`.
=> [Multi-Dependencies] Enqueuing of Dependents

rq/job.py
Logging job's description with huge arguments makes terminal unreadable and log files too large.
It would be nice if arguments with more than N characters, let's say 75, get truncated.
See #1263 #1269
=> Truncate job args/kwargs to a reasonable length

.travis.yml, requirements.txt, setup.py
Better handling of requirements by keeping them in sync and raise `redis-py` to 3.5.0.
=> Improve requirements handling

setup.py
As `redis-py` in version 3.5.0 is now required, whoch only support
Python 3.5+, we should remove Python 3.4 from the supported Python
versions as well.
Signed-off-by: Paul Spooren <mail@aparcar.org>
=> setup: Set min Python version to 3.5

.github/workflows/test.yml
Only test on major versions to reduce number of tests.
Signed-off-by: Paul Spooren <mail@aparcar.org>
=> CI: Only test redis-py 3.5.0

CHANGES.md
With revision 02eb983e90aeb8e878e5c0f9989b7b701b8ad21a the `python_requires` was set to `3.4`
=> Python 2.7 supported dropped in 1.4.0 (CHANGES.md)

rq/compat/__init__.py, rq/job.py, rq/queue.py, rq/worker.py
This is the first thing I came up with, however it's not perfect:
* I used the names `redis_version` and `connection_version`, however `library_version` and `server_version` or something entirely different might be easier to grasp?
* There is no certainty that `redis-py` 3.5.4 will actually support LPOS, I just came up with that version.
* Should the legacy and undocumented StrictVersion module be used (it's part of stdlib)
* Should `queue` contain the version information?
* There is a mixup of using the compat function `hmset` and directly `hset` in the `worker` class. Shouldn't we just raise the minimal version to `3.5.0`?
* Redis server supports `HSET` mappings starting from version 4.0, however there is no trivial way to check the version from within compat function `hmset` as a …
=> Version aware

rq/worker.py
In our systems, this bug seemed to be the cause of disappearing workers: worker keys would get a very small TTL in Redis and would eventually expire, thus mysteriously "disappearing" from dashboards.
=> Fix incorrect worker timeout calculation in SimpleWorker.execute_job

docs/docs/index.md
In general, if we enqueue one job into the queue but this job cannot be started yet, then the queue size will not enlarge.
=> [doc] notes for len(queue)

rq/worker.py, tests/fixtures.py, tests/test_worker.py
handled unhandled exceptions in horse to prevent a job from being silently dropped without going into FailedRegistry
In my case I got exceptions like this:
```
TimeoutError: [Errno 110] Connection timed out
File "redis/connection.py", line 539, in connect
sock = self._connect()
File "redis/connection.py", line 596, in _connect
raise err
File "redis/connection.py", line 584, in _connect
sock.connect(socket_address)
ConnectionError: Error 110 connecting to <url>:6379. Connection timed out.
File "rq/worker.py", line 477, in work
self.execute_job(job, queue)
File "rq/worker.py", line 670, in execute_job
self.fork_work_horse(job, queue)
File "rq/worker.py", line 610, in fork_work_horse
self.main_work_horse(job, queue)
File "rq/worker.py", line 687, in main_work_horse
raise e
File …
```
=> handled unhandled exceptions in horse

rq/decorators.py, tests/test_decorator.py
This pull request will close #1318. It allows retrying of jobs to be sat through the @job-decorator.
=> Allow retries to be set through decorator

rq/scheduler.py
`ssl` attribute is lost after forking since `redis-py` doesn't store `ssl` attribute in connection kwargs https://github.com/andymccurdy/redis-py/blob/5a6a50b50db26e4b1c4b7a6cb9b2a2caa8ba5e8b/redis/client.py#L783
Apparently this PR also fixes https://github.com/rq/rq/issues/1310
Sorry, no Idea how to write unit test for ssl connection, just tested it manually.
=> fix(scheduler): correctly restore ssl connection after forking

rq/utils.py
when I ran pytest on my app I had this warning and fixed it in this PR
`DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
from collections import Iterable`
=> fix deprecated Iterable import

.github/workflows/workflow.yml, dev-requirements.txt, rq/worker.py, tests/fixtures.py, tests/test_worker.py
by setting work horse process group and killing the whole group.
might be useful if task runs other subprocesses.
=> feat: avoided "zombie" processes after killing work horse

rq/registry.py, rq/scheduler.py, tests/test_scheduler.py
Fixes #1354 
It might not be complete fix of this issue but prevent (in most cases) bug, reducing `enqueue_scheduled_jobs` function executing time to less than 5 seconds
=> scheduler: now operates with chunks of jobs

docs/docs/jobs.md, rq/job.py, rq/worker.py, tests/test_job.py
heartbeat might be needed in cases when worker was hardkilled or the whole VM/docker was forcibly rebooted.
=> feat: added job heartbeat to track whether job is actually executing

docs/docs/workers.md
Small typo in the send_kill_horse_command() example in the workers docs.
=> Fixed typo in workers docs: send_kill_horse_command() example

README.md, docs/index.md
The former link is broken since http://flask.pocoo.org/snippets has been
taken down. See https://github.com/pallets/website/issues/41 for more
info.
=> fix snippet link in docs

rq/job.py, rq/queue.py, rq/serializers.py, rq/worker.py, tests/test_worker.py
Adds `serializer` as an argument to the `fetch_many` and `dequeue_any` methods. Also adds `self.serializer` as an argument to `fetch` calls when fetching jobs. This ensures that the worker will correctly maintain the custom serializer when pulling jobs off a queue created with a custom serializer. Likely addresses issue in #1357. Encountered and solved with @nathanielweinman
=> Fix custom serializer in job fetches

rq/worker.py, tests/test_worker.py
Resolves #1153
Could be also potential fix for #998
formatted the code following the comments made by @selwin  on #1261 . Also, added the `max_connection_wait_time` to limit max retry timeout to 60 seconds.
=> Add exception to catch redis connection failure to retry after wait time

rq/job.py, tests/fixtures.py, tests/test_fixtures.py, tests/test_job.py
Hi, I'm hoping to maybe help get the ball rolling again on Issue [#260](https://github.com/rq/rq/issues/260) with this pull request. I may be completely off-base, but thought I'd give it a shot!
The PR:
* allows lists & tuples of dependencies as the value of `depends_on`, and this is passing a first unit test.
* includes the full list of dependencies (instead of just the first) in the `Job.to_dict()` representation
Note: Before I made any changes, I ran all existing unit tests. All passed _except for the three tests in `test_commands.py`_.
Maybe I'm just missing some fixture in the test setup on my machine? Dunno.
Anyway, _with those three skipped_, all unit tests are passing on my machine after my changes.
My testing was with Python 3.8.3
=> Multidependencies

rq/job.py
Code fails when I use JSONSerializer and have dependencies. This fix solves it.
=> bugfix: Add self.serializer when calling self.fetch_many in fetch_dependencies

README.md, docs/index.md
Updated cutting edge pip install command to use HTTPS rather than insecure git+git protocol, as recommended by pip documentation. This allows the command to work with pip >= 21.0.1
This fixes issue #1439
=> Newer pip install command from git

rq/worker.py
Currently, the traceback of an exception occurring in a job ends up being printed twice:
```
15:35:23 Handling failed execution of job 8593dcd5-9b83-4342-8e7d-8d0b7ad8d39e
15:35:23 Traceback (most recent call last):
File "/Users/peter/devel/rq/rq/worker.py", line 1008, in perform_job
rv = job.perform()
File "/Users/peter/devel/rq/rq/job.py", line 706, in perform
self._result = self._execute()
File "/Users/peter/devel/rq/rq/job.py", line 729, in _execute
result = self.func(*self.args, **self.kwargs)
File "./tasks.py", line 2, in buggy
raise Exception("Whooops! A daisy!")
Exception: Whooops! A daisy!
Traceback (most recent call last):
File "/Users/peter/devel/rq/rq/worker.py", line 1008, in perform_job
rv = job.perform()
File "/Users/peter/devel/rq/rq/job.py", line 706, in perform …
```
=> prevent job exception being logged twice

rq/job.py, rq/utils.py, tests/fixtures.py, tests/test_job.py
This PR fixes a problem reported in https://github.com/rq/rq/issues/1457 - it allows to enqueue class functions decorated with `staticmethod`, like `test_job`:
```python
class TestClass:
@staticmethod
def test_job():
return 'Test static method'
```
All the existing tests and a newly created test case pass.
Unfortunately, I see at least one case, in which `staticmethod`s still can't be enqueued - it's when they're members of nested classes, like `nested_test_job`:
```python
class TestClass:
class NestedClass:
@staticmethod
def nested_test_job():
return 'Test static method'
```
I haven't implemented handling them as I'm not sure, if it's worth the effort - what do you think? :)
=> bugfix: Allow using staticmethods as jobs

rq/cli/helpers.py, rq/compat/dictconfig.py, rq/decorators.py, rq/job.py, rq/local.py, rq/queue.py, rq/registry.py, rq/scheduler.py, rq/timeouts.py, rq/utils.py, rq/worker.py, tests/fixtures.py, tests/test_sentry.py, tox.ini
Removed deprecated (object) inheritance
Add new py38,py39 versions to tox, removed deprecated py27,py34
Replace enum internal function with Enum class
=> Replace enum function with internal Enum class

rq/cli/cli.py, rq/scheduler.py, rq/version.py, rq/worker.py, tests/test_scheduler.py
1. Fixes: https://github.com/rq/rq/issues/1453
2. making cli.py compatible with click 8.x
-cc @selwin
=> Make RQScheduler work with a serializer

docs/_layouts/contrib.html
While looking through the code I saw that there are some contributing pages without links from the website.
It is a very small fix so I didn't create any issue.
=> Bug: Website Contributing Pages

rq/utils.py
Sometimes the failure during importing is due to a genuine coding error in the imported module. In this case, the exception is logged as a warning for ease of debugging of the imported user code.  The logic is unchanged and it will be applied anyways regardless of the cause of the import error.
A case where it seems beneficial to have more feedback on the import error has been reported in issue #1488
=> Added logging trace for failed import for user-level debugging

docs/docs/index.md, docs/docs/jobs.md, rq/queue.py, rq/version.py, tests/test_queue.py
Resolves #753 
See also: #241
Allow user to pass in a `pipeline` argument to the enqueue methods.
One main use case is the ability for the caller to use their own pipeline and still be able to utilize the dependency logic defined in `enqueue_call`.
-cc @selwin
=> Make `Queue.enqueue`, `Queue.enqueue_call`,  `Queue.enqueue_at``Queue.parse_args` accept `pipeline` arg, add `Queue.enqueue_many` method

rq/job.py, rq/utils.py, tests/test_utils.py
Let's say you want to enqueue invocation of the following function: `f(arg1, arg2, secret_passphrase)`.
Currently, to avoid logging `secret_passphrase`, possible solutions include disabling logging or providing custom `Job.description`.
If you want to mimic rq's default `Job.description`, you have to create a fake `Job` with `func_name`, `args` and `kwargs` attributes. Then you can call `Job.get_call_string(fake_object)`. Such workaround has a potential to break application when the implementation details of `Job` change.
Move `Job.get_call_string` logic to `utils` with the following signature `get_call_string(func_name, args, kwargs)`. This way that helper function can be used by applications, for example in the following way:
```python
func_name, args, kwargs = ..., ..., ...
q = …
```
=> Extract `Job.get_call_string` logic to `utils.get_call_string`

rq/worker.py
The `CLIENT` redis command is not supported in Google Memorystore Redis. This PR catches the `ResponseError` thrown when `rq` tries to use the `CLIENT` command, logs a warning and sets the `ip_address` to `"unknown"`.
See https://github.com/rq/rq/issues/1508 for related issue.
=> Handle ResponseError when CLIENT command is not supported

rq/queue.py, tests/test_queue.py
Re: https://github.com/rq/rq/issues/1416, this PR updates queues with `is_async=False` to respect job result TTLs.
The issue diagnoses the problem correctly. The new tests cover the `Queue.run_job` method, which is making the `cleanup` call.
=> Issue 1416: Use result_ttl for synchronous queues 

docs/docs/jobs.md, rq/job.py, tests/test_job.py
The newly introduced function returns meta data stored for the job. This
is required since job.meta stays an empty dict until the job is
finished or failed.
With the new function it's possible to store arbiatraty states/stages of
the job and allow the user to track progress. A long running job may
return custom stages like `downloading_data`, `unpacking_data`,
`processing_data`, etc.
This may allow better interfaces since users can track progress.
Signed-off-by: Paul Spooren <mail@aparcar.org>
=> job: add get_meta() function

docs/docs/workers.md
The link within the [Custom Worker Classes](https://python-rq.org/docs/workers/#custom-worker-classes) section currently does not work. Changing it to be all lowercase fixes that.
=> Fix link Round Robin / Random worker classes

rq/cli/cli.py, rq/version.py
Making a quick patch fix (and bumping the patch version) to pass serializer across the cli commands.
Tests were not added because it does not break immediately, the example that came up was only later when maint tasks were being run to clean up registries.
=> Pass serializer to queue at cli

rq/worker.py
In #1496, we observed a situation where the `work()` method crashes after
`.subscribe()`, but prior to the `try/except` block which normally cleans up
after `.subscribe()`.
Specifically, `.subscribe()` launches a thread in non-daemon mode. Because of
that setting, Python will keep the calling worker process active, even if the
main thread has crashed. This resulted in a syndrome where a worker process was
running, but doing no work.
The change launches this thread in daemon mode, i.e. prevents a "zombie" pubsub
thread from keeping the process up.
(An additional change we could make, discussed in #1496 but deferred, would be
to improve the error handling/trapping scope in `.work()` such that all
failures trigger resource cleanup.)
=> bugfix: worker: Launch pubsub thread in `daemon` mode.

rq/job.py, tests/test_job.py
The `job.cancel` function was calling `remove` on the queue, assuming a job is in a queue, not in a registry, this assumption should not be made and this change ensures that it checks not only the queue but also its registries.
Would be nice to get this merged before #1562 is done.
=> Fix `job.cancel` to remove job from registries if not in queue

rq/job.py
Apparently, the `remove_from_queue` argument of `Job.delete()` must be passed to `Job._remove_from_registries()`.
Fixes #1598
=> Fix `Job.delete()` with `remove_from_queue` argument

rq/job.py, tests/test_job.py
**TL;DR:**
This bug has opened a lot of possible race-conditions, since the watch-logic from redis did not fail anymore, if dependencies have been changed in parallel.
This seems related to #758, especially https://github.com/rq/rq/issues/758#issuecomment-791603930, where jobs were hanging in deferred state, but I can't say, that my changes fix all issues in #758.
**Details:**
I found this issue during an upgrade of a project from RQ 0.13.0 to 1.10.1, which heavily uses job dependencies. Fortunately, during first tests I saw hanging jobs in "deferred" state.
Actually, I'm a co-author of the whole watch-logic for dependencies introduced in RQ 0.7.1, which has fixed race-conditions for single dependencies here: https://github.com/rq/rq/issues/739
Unfortunately, with the switch to multiple …
=> Fixed wrong keys used to WATCH dependencies

rq/queue.py
I've found another bug in the dependency handling, which seems to be introduced with https://github.com/rq/rq/commit/456743b225c0b5a4339242a5b714c378b86f2fe0. It results in no job execution, if unfinished dependencies exist at the beginning, but all of them get finished in parallel.
**More details:**
If all of the unfinished dependencies get finished in parallel to the enqueuing of the job, the `execute()`-call will fire a WatchError [here](https://github.com/rq/rq/blob/c5a1ef17345e17269085e7f72858ac9bd6faf1dd/rq/queue.py#L368). This will leave the `job` instance in a changed state, where status is set to `DEFERRED` ([see](https://github.com/rq/rq/blob/c5a1ef17345e17269085e7f72858ac9bd6faf1dd/rq/queue.py#L363)).
In the following retry, no unfinished dependencies would be found, so the …
=> Fixed job not getting enqueued due to parallel modification

rq/worker.py, tests/test_worker.py
The state should already have been set properly by the worker in
`execute_job`
`prepare_job_execution` is only called by `perform_job` which should only be
called by `main_work_horse`/`fork_work_horse` (themselves only called by `execute_job`).
Let `execute_job` do the bookkeeping.
=> rq.worker: remove useless set_state call in horse

rq/decorators.py, tests/test_decorator.py
This PR allows the job decorator to use the on_failure and on_success functions in the job. fix #1626
=> job decorator allow on_failure and on_success parameters

docs/docs/testing.md, rq/timeouts.py, rq/worker.py, tests/test_timeouts.py
Replaced `SimpleWorker`'s use of signals that are not available on Windows platform with a `threading.Timer` approach that should be platform-agnostic and allow for local testing.
Tests related to `SimpleWorker` pass:
`pytest ./tests/test_worker.py::TestWorker::test_work_via_simpleworker`
`pytest ./tests/test_worker.py::TestWorker::test_simpleworker_heartbeat_ttl`
Closes #1625
=> Cross platform simple worker

docs/css/screen.css
Hi there!
Thank you very much for creating this! I've been using it for over a year and it's brilliant!
I had a small problem while browsing the docs: I wanted to click on "Jobs" section, and was sure that i'm selecting it, but i kept landing on "scheduling":
Until i realized this is just two words broke in half :joy:
I added one css line to prevent that in future:
=> Docs: don't break links at the header

README.md
The old domain has been compromised. See https://github.com/celery/celeryproject/issues/52 for more information.
=> Update link to Celery website

docs/docs/index.md
Adds a missing colon in function arguments
=> Fix syntax error in docs example

dev-requirements.txt, tests/test_decorator.py, tests/test_queue.py, tests/test_scheduler.py, tests/test_sentry.py, tests/test_utils.py, tests/test_worker.py, tests/test_worker_registration.py, tox.ini
This module has been included in Python itself since 3.3.
Fixes: https://github.com/rq/rq/issues/1646
=> Use unittest.mock instead of mock

rq/queue.py
The `on_success` and `on_failure` callbacks are currently supported in `Queue.enqueue` but not `Queue.enqueue_many`, despite documentary indicating the contrary.
This commit brings the bulk enqueuing API back into parity.
Fixes #1680
=> Support callbacks in enqueue_many

.github/workflows/lint.yml, rq/cli/cli.py, rq/cli/helpers.py, rq/compat/__init__.py, rq/compat/connections.py, rq/decorators.py, rq/job.py, rq/utils.py, rq/worker.py, setup.cfg, tests/fixtures.py, tests/test_cli.py, tests/test_decorator.py, tests/test_queue.py, tests/test_registry.py, tests/test_scheduler.py, tests/test_utils.py, tests/test_worker.py
@selwin Here's some lint fixes (about half fixed) as promised, but there's still some outstanding
```
./tests/test_cli.py:442:121: E501 line too long (138 > 120 characters)
./tests/test_cli.py:647:121: E501 line too long (121 > 120 characters)
./tests/test_cli.py:653:121: E501 line too long (130 > 120 characters)
./tests/test_cli.py:659:121: E501 line too long (134 > 120 characters)
./tests/test_cli.py:683:121: E501 line too long (125 > 120 characters)
./tests/test_cli.py:689:121: E501 line too long (132 > 120 characters)
./tests/test_cli.py:695:121: E501 line too long (130 > 120 characters)
./tests/test_cli.py:701:121: E501 line too long (134 > 120 characters)
./tests/test_cli.py:707:121: E501 line too long (131 > 120 characters)
./tests/test_cli.py:713:121: E501 line too long (135 > 120 …
```
=> Improve the lint situation

rq/worker.py
Job status is not yet "stopped" when determining the log to print in `monitor_work_horse`
=> Fix log on job stop

docs/docs/workers.md
In introduction, we say that queue order matters, but we are not very specific.
Added a paragraph to explicit that.
=> doc: default queues order is a priority order

.github/workflows/docker.yml, .github/workflows/workflow.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

rq/queue.py
`rq.queue.Queue.enqueue_many` is used to enqueue many jobs in one go on `rq` in a bulk operation. 
The issue is that it calls `rq.queue.Queue.enqueue_job` which in turn calls `rq.job.Job.save` which calls `rq.job.Job.get_redis_server_version` which does a round-trip to the server to get the server version. This is cached in `Job`, however when enqueuing 1000 jobs all of these caches are empty. So calling `enqueue_job` on 1000 jobs will do 1000 round-trips to the server to get the server version, which is very slow. 
The patch pre-warms the `Job` cache, causing the round-trip to the server to only happen once.
=> pre-warm redis server version cache of job from queue

.github/workflows/codeql.yaml, .github/workflows/dependencies.yml, .github/workflows/docker.yml, .github/workflows/lint.yml, .github/workflows/workflow.yml, rq/worker.py, tests/test_worker.py
Persisting the worker_name on the job object in Redis would allow for debugging and analyzing logs from the worker
=> Persist worker_name after job is finished

rq/utils.py, tests/test_utils.py
Hi there, long time `rq` user here.
I was recently running some annual disaster recovery tests in our infra. These tests involve enqueuing hundreds of thousands of objects in our `rq` and then running scripts to evict duplicated jobs. To my surprise, enqueuing the objects would take about a day or so, while last years test took a few seconds.
Upon further inspection and profiling it became aparent that the reason for the low performance was a `get_redis_server_version` call for every job. And caching or hard-coding that value would help the performance issue.
Here's a proposal to sneakily store the server version on the connection object, this would make enqueue calls fast again as long as they are made from the same connection.
=> Cache redis version in the connection object

rq/queue.py, rq/worker.py
There were reports where a worker wouldn't fetch new jobs.
Since one possible cause is the infinite hanging of the `BLPOP` command,
this adds a couple of logs surrounding the `dequeue_any` function,
that interacts with Redis using `BLPOP`,
=> Enhance debug logs

rq/queue.py, rq/utils.py, rq/worker.py
There is a helper funcion that excludes `None` values from a list. This was being declared both in the Queue and in the worker. This centralizes this helper in the `utils` Importing
=> Moves the `compact` helper to `utils`

dev-requirements.txt, rq/command.py, rq/connections.py, rq/decorators.py, rq/defaults.py, rq/job.py, rq/serializers.py, rq/types.py, rq/utils.py
- Improves docstrings on the `connections` module.
- Adds docstrings to all methods on the `Job` class.
- ~Adds a `Protocol` to define serializers (`dumps` and `loads` methods)~ (this only exists in 3.8, excluded)
Still missing (next PR)
- Standardized docstrings for `Queue`
- Standardized docstrings for `Worker`
@selwin sorry this is fairly big, but it's a lot easier to do it all at once than N PRs with a single docstring each.
There's little to no change in logic, so this should be mostly reviewing the docs.
As this is fairly large, it would be preferable to not leave this hanging for too long, since it would cause quite a bit of conflict on future PR's which would be a huge pain to deal with.
=> Job methods docstrings

rq/queue.py
When running on debug mode, some debug logs were
using colorizers on lists, which would raise an unhandled exception on the worker.
The same happened for a debug log that was using colors on a response from Redis (bytes).
To avoid changing the colorizer functions signature, I chose to fix this manually.
In the future we could have more robust logic for the colors (deconstruct lists, convert bytes to string, etc).
Fixes #1786
=> Bugfix: Fix bug when running worker on debug mode

rq/worker.py, tests/test_worker.py
result might be None if burst=True for example
added a test (failing before the fix)
(This was introduced in #1752)
=> Fix - TypeError - accessing None when dequeued result is None (when timeout=None, e.g. in burst mode)

rq/job.py, rq/queue.py, tests/test_callbacks.py
Fixes https://github.com/rq/rq/issues/1797
=> Use job.return_value() instead of job.result when processing callbacks

rq/contrib/legacy.py, rq/worker.py, tests/test_worker.py
Worker ttl was ignored.
BTW, do we have a better name for `timeout`? It was names `_get_timeout` before, but maybe something more specific can help with readability
=> Fix - Use worker TTL for timeout

docs/docs/connections.md
=> docs: add warning of `decode_responses`

rq/utils.py
With reference to: https://github.com/rq/rq/discussions/1828
I decided to completely remove the logger line instead of changing it to `debug`, because in all cases during my observation, there was nothing happening that was worthy of a log. 
In case of a class method, the function moves through each component of the dotted path (raising and catching `ImportError`s as needed) till it found a module to import, which is the expected behavior.
=> removed import error warning and changed function doc

docs/patterns/index.md
Redis To Go no longer exists. The section is replaced with instructions for Heroku Data For Redis
=> (Docs) Updated patterns - heroku

rq/timeouts.py, tests/test_timeouts.py
I believe the intended behavior when job timeout is negative is to have infinite timeout. However, `TimerDeathPenalty` immediately times out jobs instead. This PR fixes that behavior and adds a test for that case.
=> Fix TimerDeathPenalty not properly handling negative/infinite timeout

docs/docs/workers.md, rq/cli/cli.py, rq/cli/helpers.py, rq/job.py, rq/queue.py, rq/results.py, rq/utils.py, rq/worker.py, rq/worker_registration.py, tests/test_cli.py, tests/test_worker.py
This implements a new parameter `dequeue_strategy` that should replace the `RoundRobinWorker` and `RandomWorker`.
It adds the parameter to (1) the `work()` method, (2) the `Worker` constructor and (3) to the CLI. It also adds deprecation warnings to the workers: I chose to do this through the CLI to avoid having to have a `__init__` method on the workers, and to avoid showing this warning only when the workers hits the `reorder_queue` method - that way we can have the warning as soon as possible.
Fixes #1805
=> New dequeue strategy

docs/docs/connections.md, rq/cli/helpers.py, tests/test_helpers.py
resolves #1849 
- added `USERNAME` key
- added `CONNECTION_KWARGS` key to allow passing additionals arguments to the Redis connections
- updated the documentation
=> Update arguments passed to the Sentinel Object when created from the settings

docs/docs/connections.md, rq/__init__.py, rq/connections.py, tests/test_connection.py
The deprecation warning for `use_connection` first appeared when the docs moved to this repo (~2019 if I'm not mistaken), this effectively removes the `use_connection` from the codebase. This is also the first step to completely eliminate `local` from the codebase: we are still missing deprecating `push/pop` connections, which are only used by the worker on the `perform_job` method, and the `with Connection` context manager, which already has a deprecation warning in place.
=> Remove `use_connection`

rq/connections.py
Most of the functions on the `connections` module are used to interact with a Redis connection implicitly through the LocalStack: `push/pop/use/resolve_connection`.
The connection ideally should be handled explicitly and the `with Connection` already has a deprecation warning. This adds deprecation warnings to those functions. After these are deprecated, we would be able to delete the `local.py` entirely, and only handle connections explicitly.
=> add deprecation warnings to connection functions

rq/worker.py
Removes the `resource` import (that breaks usage for Windows), and wraps it to `try/except` block while type checking so that we still have the same effect on POSIX platforms.
Needs testing on Windows.
Fixes #1848
=> bugfix: type annotations as str to allow Windows usage

docs/docs/index.md
Currently the code in the example causes `TypeError: 'http://nvie.com' is not a valid args list`.
The solution that @rpkak proposes works. Closes #1524
=> Fix error in example in the documentation

docs/patterns/index.md, rq/cli/helpers.py
Each queue and each worker has info about finished/failed jobs
Didn't add ' [num of jobs] executing ' to worker bc it ias the same as 'busy'
```
default      |██████████████ 35, 2 executing, 0 finished, 0 failed
1 queues, 35 jobs total
1a0a9f8ae1364fb4b13bbb7763a4fc74 (None None None): busy . jobs: 0 finished, 1 failed
0bdc85d1b78842a497aef2e7f71b147c (TiH-MacBook-Pro.local [::1]:50568 21446): busy default, high, low. jobs: 0 finished, 0 failed
2 workers, 1 queues```
=> Added job details to "rq info" command

docs/docs/results.md
When a job gets stuck in WIP state, e.g. because the worker was killed or lost its network connection, the job eventually ends up in `FailedJobRegistry` with an `exc_info` value of `Moved to FailedJobRegistry at 2023-02-2(...)`. As far as I can see, this isn't documented anywhere at the moment. This just adds a small paragraph explaining the behavior.
The whole topic of zombie jobs and `StartedJobRegistry.cleanup` probably deserves a dedicated section in the docs. I am just not sure where exactly to put it?
=> improve the docs on in-flight jobs of killed/lost workers

setup.py
This allows external projects that use type checkers themselves to read the typing information that RQ contains.
Without this file, compliant type-checkers will skip type checks for project code that calls RQ.
Fixes #1881
Note: this PR should be backwards compatible to pretty much any branch, so if there are more versions maintained than just master branch, applying the same patch to them would allow older versions to type check without upgrading to the latest version of RQ.
1. Create test file `example.py`:
```lang=py
from redis import Redis
from rq import Queue
q = Queue(connection=Redis())
result = q.enqueue(sum, [1,2,3,4,5])
```
2. (optional: create virtual environment first) Install dependencies
`pip install mypy redis types-redis rq`
3. Run MyPy `mypy example.py`
Should observe MyPy …
=> Add py.typed for PEP561 compliance

rq/connections.py, rq/scheduler.py, tests/test_scheduler.py
Following https://github.com/rq/rq/issues/1879, I'm proposing a change to allow passing a **custom connection class to the scheduler**;
To date, we can pass a custom connection to a worker with:
```python
my_custom_conn = redis.Redis(
connection_pool=redis.ConnectionPool(
connection_class=CustomRedisConnection,
custom_arg="foo",
)
)
worker = Worker(connection=my_custom_conn)
worker.work()
```
but doing so while enabling the scheduler will raise:
```python
worker.work(with_scheduler=True)
```
Passing extra arguments to the connection pool class is a standard feature in redis-py, as per the [documentation](https://redis.readthedocs.io/en/stable/connections.html#redis.connection.ConnectionPool).
I added 2 tests to verify that the custom connection class is indeed used, and that it does not …
=> [Fix] Allow custom connection pool class for the scheduler

rq/defaults.py, rq/job.py, rq/results.py, tests/test_results.py
Hi 👋🏼 
Before RQ 1.12, RQ was actually allowing unserializable results in `job.save()` ([here](https://github.com/rq/rq/blob/master/rq/job.py#L977)):
```python
try:
obj['result'] = self.serializer.dumps(self._result)
except:  # noqa
obj['result'] = "Unserializable return value"
```
RQ 1.12 introduced a breaking change in this regard, as we're now storing the result also in a proper `Result` object to keep multiple results ([here](https://github.com/rq/rq/blob/master/rq/results.py#L184)):
```python
serialized = self.serializer.dumps(self.return_value)
```
This PR proposes to be less strict and allow unserializable results (as before).
I'm also adding a test that tries to save a known non-picklable value (`tempfile.NamedTemporaryFile()`) to assess that it doesn't break
Happy to have …
=> [Results] Allow unserializable return values

rq/job.py, tests/test_worker.py
@selwin I came into a rare error where a job meta is stored on job_failure, but it crashes the worker when loading the job (the worker fails completely)
Please let me know how to go about it. In the meantime, I'm using this branch...
=> Catch serializer TypeError Exception

rq/connections.py, rq/scheduler.py, rq/worker_pool.py, tests/test_connection.py, tests/test_worker_pool.py
It seems that we were unnecessarily [changing the connection pool kwargs](https://github.com/tchapi/rq/blob/5bf8239ea2a8378a6d0e344fcf80aaa07bcb37f3/rq/connections.py#L126-L135) because we were trying to pass them to a Client instead of a ConnectionPool:
```python
if issubclass(connection_pool_class, SSLConnection):
connection_kwargs['ssl'] = True
if issubclass(connection_pool_class, UnixDomainSocketConnection):
connection_kwargs['unix_socket_path'] = connection_kwargs.pop('path')
```
Now that we're correctly using a ConnectionPool (since #1885), we don't need those changes anymore
=> [Hotfix] Fix SSL connection for scheduler

.github/workflows/workflow.yml, tox.ini
**Problem 1️⃣**
Environment variables are not passed to pytest via tox if they are not explicitly registered in the tox configuration
The SSL tests and SLOW tests were not run while using `make test` 
**Problem 2️⃣**
SSL tests were not run by the Github actions since it requires a TLS-enabled Redis instance. To correct this, I use the repository Dockerfile to spin off the complete test suite in Docker, with the correct Redis server. This is a supplementary job to be run by the CI -  it's quite long but we may be able to limit it to only the SSL tests? Happy to discuss
~As expected (I'm based on the `master` branch), the tests fail in the same way than this: https://github.com/rq/rq/issues/1892, but https://github.com/rq/rq/pull/1894 will fix it~
=> [Chore] Fix test suite

rq/connections.py, rq/job.py, rq/queue.py, rq/registry.py
Fix #1907
The function `resolve_connection` is now deprecated and doesn't need to be called from lots of places by default.
Now `resolve_connection` will only be called if `connection` has not been passed through already.
This should probably be done for `push_connection` also, but not in this PR.
=> Stop calling deprecated function `resolve_connection`

rq/worker.py
In certain conditions, a worker "instance" in Redis only have several (but not all) keys, example:
```python
In [5]: redis.hgetall("rq:worker:fcc8271baa9e4e4997d4e454968e29fa")
Out[5]: {b'successful_job_count': b'1', b'total_working_time': b'20.311284'}
```
In this case, `worker.refresh()` will fail because it expects all other keys (`queues` for instance) since `as_text` doesn't accept `None` values since https://github.com/rq/rq/commit/36f5c88ca21ff30fb799e7d10b2f7b9bef4e585a
Fixes #1912
=> [Bugfix] Fix `as_text` in certain conditions

.github/workflows/workflow.yml, tests/__init__.py, tox.ini
Following [this comment](https://github.com/rq/rq/pull/1911#issuecomment-1552758192):
- actually we only test Ubuntu's packaged Redis version (5.0.7 if I'm [not mistaken](https://packages.ubuntu.com/focal/database/redis))
- it takes a while because all tests are run for every tox env
- I'm proposing a modification so that only specific SSL tests are run on the `ssl-test` job, and only for the Python 3.10 env (_see tox config file_)
- We still only test against 5.0.7 but I think it's fine for now
It's quicker now.
=> [Tests] Only run SSL tests in Docker

rq/queue.py
I added a 2nd queue to my worker today and saw the debug string as:
* `Starting BLPOP operation for queues rq:queue:defaultrq:queue:snitch with timeout of 405`
* `BLPOP Timeout, no jobs found on queues rq:queue:defaultrq:queue:snitch`
and wanted to fix this to be more readable.
=> Update log string for better output when multiple queues

rq/__init__.py
`mypy` complains with "implicit reexport disabled" when importing directly from the main `rq` package, eg.
```python
from rq import Worker
```
Without adding an `__all__` to `__init__.py`, mypy would expect it this way:
```python
from rq.worker import Worker
```
This PR does add the `__all__` to `__init__.py` to please mypy.
=> Add __all__ to please mypy

rq/worker.py, tests/test_worker.py
https://docs.python.org/3/library/logging.html#logging.Logger.debug
self.log.error is called with arguments so % formatting operations are performed on the msg string. 
Before this PR exc_string was appended to the msg string and the new msg string if passed to the logging module. If exc_string contains, for example, %s it will be treated as a variable to be filled and the logging module will look for args to fill it. This will raise an exception if there are not enough args or the wrong args will get used.
This can be re-produced by raising an exception like this in a worker:
```python
raise Exception('desc %s' % value)
```
"raise Exception('desc %s' % value)" will be in exc_string and therefore part of the msg before this PR
The fix is not to append exc_string to msg but to include is …
=> pass exc_string as an argument to log

Makefile, dev-requirements-36.txt, dev-requirements.txt
This PR add a "lint" target to the Makefile 
~~It also adds black and ruff to the dev-requirements~~
It does not add black and ruff to dev-requirements because ruff does not work with python 3.6 and adding those dependencies seems to cause the tests to fail for other python versions. I guess because they cause some version change of related dependencies which are specified without locked versions
=> add lint target in Makefile

rq/job.py, rq/queue.py, tests/test_worker.py
I ran into a problem when we canceled a running parent job and the dependent jobs were executed.
When rq cancel a running job the status is changed in the database but when rq tries to enqueue the dependent jobs it seems like it does not fetch the new value from the database.
I do not know that much about the internals of RQ, could be better ways to fix this.
Probably fixes #1902
=> Do not run dependent jobs when parent is canceled

CHANGES.md
Version 1.15 added a new requirement for Redis 4.0.0 or greater. I didn't find out about this requirement until updating our dependencies. I think it would be helpful to add to the changelog.
Thank you for maintaining this wonderful library.
=> Update CHANGES.md to show change in Redis library requirement

.github/workflows/dependencies.yml, .github/workflows/workflow.yml, CHANGES.md, docs/contrib/testing.md, setup.py, tests/Dockerfile, tox.ini
The Docker tests were failing for me since psutil was trying to compile and looking for Python headers. With the python dev packages added these now work again.
Python 3.6 is skipped during the test runs presumably because the deadsnakes packages no longer build Python 3.6. So this could be removed later as part of an overall update to drop support. I'm leaving it as-is for now.
=> Add the Python dev packages for Python headers to tests/Dockerfile

rq/queue.py, tests/test_callbacks.py
stopped_callback was not being copied from the EnqueueData instance to the Job instance when using `enqueue_many`.
=> Fix bug with stopped callback in enqueue_many

rq/worker.py, tests/fixtures.py, tests/test_queue.py, tests/test_worker.py
In 9adcd7e50c511ceba622ba20c826a0b701a917ea a change was made to make the workhorse process into a session leader. This appears to have been done in order to set the process group ID of the workhorse so that it can be killed easily along with its descendants when `Worker.kill_horse()` is called.
However, `setsid` is overkill for this purpose; it sets not only the process group ID but also the session ID. This can cause issues for user jobs which may rely on session IDs being less-than-unique for arbitrary reasons.
This change switches to `setpgrp`; this sets the process group ID so that the workhorse and its descendants can be killed *without* changing the session ID.
=> Don't use `os.setsid()` after forking workhorse

docs/patterns/index.md, rq/cli/helpers.py
Currently SSL CA can only be passed in via a file in disk. `redis-py` allows passing the value as a string.
=> Allow CA be passed as a variable

docs/docs/workers.md
Fixes two typos (`serialzers` -> `serializers`) in workers.md
=> Typo: serialzers in workers.md

rq/cli/cli.py, tests/test_cli.py
the _quiet_ option for **worker_pool** is not working correctly (as **worker** does).
=> Fix 'quiet' option for 'worker_pool' comand

docs/docs/workers.md
=> docs: fix typo in `workers.md`

rq/utils.py
Currently, with Redis engine 7.1, and `redis` client 5.0.1 trying to enqueue a new job yields
```text
AttributeError: 'float' object has no attribute 'split'
```
This is caused by the fact that `redis_conn.info("server")["redis_version"]` returns a `float`, not a `str`.
The exact environment is [AWS Serverless Redis](https://aws.amazon.com/blogs/aws/amazon-elasticache-serverless-for-redis-and-memcached-now-generally-available/)
=> fix: cast redis server version from `float` to `str`

rq/utils.py, tests/test_worker.py
Replace datetime.datetime.utcnow() which will be depreceated in the future with the timezone aware datetime.datetime.now(datetime.timezone.utc).
This change is in regards to issue https://github.com/rq/rq/issues/2044#issue-2146821884
=>  Replace deprecated utcnow() with timezone aware now() 

rq/job.py
The type introduced in #1772 does not match the method description and behaviour. None is part of the returned list (line 628)
=> Fix fetch_many method type

docs/docs/index.md
Missing docs for a killer feature. Closes https://github.com/rq/rq/issues/1435
=> Document suspend and resume commands

docs/docs/jobs.md
Documenting the different job status and what they mean.
I found myself needing to coordinate the work across multiple jobs, and I wasn't quite sure what exactly each status meant. I went through the codebase and took notes, so I'm writing this down in the documentation for others to benefit as well!
Feedback is very well appreciated. :)
=> doc: Job statuses descriptions

docs/_layouts/default.html
The image URL is broken. Replace it with the "official" URL found at <https://github.blog/2008-12-19-github-ribbons/>.
=> Fix the "Fork me on GitHub" ribbon

docs/docs/index.md
=> fix docs: use delay when using @job decorator

rq/queue.py, tests/test_queue.py
Without this change queues initialized with only deferred jobs are not
listed by `rq.Queue.all()`.
=> Register queue also for deferred job

rq/worker.py
I got this error when sharing Redis DB with other clients
```
│   File "/app/manage.py", line 15, in <module>
│     execute_from_command_line(sys.argv)
│   File "/app/.heroku/python/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
│     utility.execute()
│   File "/app/.heroku/python/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
│     self.fetch_command(subcommand).run_from_argv(self.argv)
│   File "/app/.heroku/python/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
│     self.execute(*args, **cmd_options)
│   File "/app/.heroku/python/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
│     output = self.handle(*args, …
```
=> fix case when client does not have a name

rq/registry.py
Augment the warning within the cleanup task to also log the job id. This is very useful in retrospectively analysing logs.
=> More verbose AbandonedJobError warning

rq/job.py
The current type hint of `Retry` makes MyPy check failed when user passes a tuple to `interval` parameter, though that usage is correct.
=> Make Retry type hint more exact

rq/worker.py
This closes https://github.com/rq/rq/issues/1641
When dealing with any queue system at scale, you need to identify slow jobs and understand issues related to potential concurrency problems between workers.
In addition, this logging gives system administrators an overview of what happened in the past when debugging difficult problems.
Because logging _what_ jobs got completed _when_ is as fundamental to a job system as an access log is to a web server. It helps the programmers monitor _their_ code (whereas debug level in the `rq` library gives insight into the `rq` internals and would be too much info for a typical persisted log)
Here's an example of the output
```
[INFO] Successfully completed snakes.tasks.populate_projects_iso_matches() job in 0:00:00.066600s on worker …
```
=> Log job success

rq/worker.py, tests/test_worker.py
This change checks for Redis connection socket timeouts that are too short for operations such as BLPOP, and adjusts them to at least be the expected timeout.
=> Ensure the Redis socket timeout is long enough for blocking operations

rq/utils.py, tests/test_utils.py
Converts float to a string in cases where the redis server does not return a string (such as AWS's Elasticache Serverless Redis service). I have not tested AWS Elasticache On-Demand Redis, so this may fix the same issue if it also occurs with that AWS service.
Also ensures that a tuple of 3 integers is returned, even though AWS only returns versions in the format `7.1`.
Closes #2130
=> [AWS Elasticache Serverless Redis] Handle redis servers that return non-string versions

rq/registry.py, tests/test_registry.py
Prior to this commit it was not possible to get a number of jobs in a registry or list job IDs without triggering a cleanup. Calling cleanup caused issues for:
* Monitoring tools (see https://github.com/rq/rq/pull/2104) and
* Cases with high number of jobs in the registries (see https://github.com/rq/rq/pull/2003).
* Cases where a failure callback is registered and but the `get_job_ids` is called not from the main thread (see https://github.com/rq/rq/pull/2104#issuecomment-2397114656).
In this commit:
1. A new `BaseRegistry.get_job_count` method is added. It is a side effect free version of `BaseRegistry.count` and runs in O(1).
2. A `cleanup` parameter added to `get_job_ids` that allows to avoid clean up if it is set to `False`.
Resolves https://github.com/rq/rq/pull/2104.
Resolves …
=> Allow to get job count and job IDs without cleanup

rq/worker.py, tests/fixtures.py, tests/test_commands.py
Hi,
This is proposal to fix issues #1836 & #2070
After a connection error to Redis the pubsub thread was stopped and the worker could not receive commands anymore.
This commit adds an exception handler for the thread that adds a log message and ignores `redis.exceptions.ConnectionError`. Any other exception is re-raised.
redis-py internal mechanism allows the pubsub thread to recover its connection and reinstall the pubsub channel subscription to allow the worker to receive commands again after connection errors.
It tries to behave the same as the main worker loop retry mechanism but without the backoff wait factor because we're not operating in a loop.
=> Add an exception handler for the pubsub thread

rq/cli/cli.py, rq/worker_pool.py
@selwin I happened to be looking at https://github.com/rq/django-rq/pull/683 and I noticed a few more uses of the concrete class that should be the protocol
=> use `Serializer` Protocol instead of concrete `DefaultSerializer`

rq/queue.py, tests/test_queue.py
=> Set ended_at for a job when using is_async=False

rq/group.py, tests/test_group.py
This was causing a bug when workers call `run_maintenance_tasks`, which involves cleaning up groups whose jobs have expired. 
If the group has already been deleted from Redis, due to all member jobs having been manually deleted with `job.delete()`, then the `Group.all()` method will raise a `NoSuchGroupError` as it iterates through the `rq:groups` set. 
This change will handle the `NoSuchGroupError` and remove the missing group from the registry.
=> Delete expired groups from registry

rq/queue.py, tests/test_queue.py
In https://github.com/rq/rq/commit/df5e99ba0b3274ab734cde612c270a788ee47ffc, the call to `sadd` new Queues to the `rq:queues` registry was moved from `queue._enqueue_job` to `queue.enqueue_job` due to `_enqueue_job` not being called on jobs that are deferred.
However, this broke the `queue.enqueue_many` function, which has its own handling for deferred jobs. Now, `enqueue_many` does not add the queue to `rq:queues`.
This change copies the `sadd` call to `enqueue_many` and tests that the registry contains the queue after the method is called.
=> Add new queue to registry in enqueue_many

rq/worker.py
My understanding of how this works could be wrong. So please take a look at it carefully.
Currently, each worker spawns a pub-sub thread to listen for shutdown or stop/kill job commands. This thread polls every 0.2 seconds.
The 0.2 seconds on its own doesn't do anything, Redis' socket connection can block on it forever if you just specify `sleep_time=None`, but now that thread will be permanently blocked until its blocking `recv` ends with a response from Redis.
There are three solutions here:
- We can increase timeout, this will increase the time it takes to shut things down.
- The thread doesn't "need" to be joined, it's a daemon thread and if it dies without joining with a worker it shouldn't be a problem.
- We can set blocking behavior AND unsubscribe pubsub before joining the thread. …
=> perf: Avoid polling in PubSub thread

rq/cli/cli.py, rq/cli/helpers.py, rq/worker.py
FIX Bug From #1702 
Only resolve bug that Worker override logging configuration.
Just set INFO if logging is logging.NOTSET. Otherwise,`None` is passed, makes not override default logging level.
=> FIX bug worker override logging configuration

rq/cli/cli.py, rq/dependency.py, rq/group.py, rq/job.py, rq/queue.py, rq/utils.py, rq/worker.py, rq/worker_pool.py, tests/test_utils.py
Many functions declare input parameter type as `List[T]` but only need to iterate over it. This PR changes the type of `Iterable[T]` or `Sequence[T]` to let user pass `tuple`, `deque`, generator.
`Iterable` is broader than `Sequence`, allowing user to pass generator. But a generator can only be iterated once (after that, it will exhaust), so if the function uses that argument twice, we limit the type to `Sequence`.
I also change some type hint from `Any` to generic type (using `TypeVar`) because `Any` makes type checker (MyPy, Pyright useless).
(This is a rework of #2146).
We will need more PR to get rid `Any` type.
For discussion:
I observe that many function return data as a list, but that data then is not mutated. In that case, I think we better use `tuple` because it is has lower …
=> Lift restriction on function parameter types

rq/queue.py
Fixed several spelling mistakes throughout the Queue class to improve documentation quality:
- 'kargs' → 'kwargs' in Queue.parse_args docstring
- 'kargs' → 'kwargs' in Queue.enqueue docstring
- 'registerd' → 'registered' in Queue.all method
- 'enqued' → 'enqueued' in Queue.enqueue_job docstring
- 'ommited' → 'omitted' in finished_job_registry TODO comment
- Updated docstrings and comments to use correct spelling
- No functional changes, documentation improvements only
=> docs: fix spelling mistakes in Queue class docstrings and comments

rq/worker_pool.py
Seems like a simple programming mistake.
=> (minor) Fix WorkerPool.status never set to STARTED

rq/job.py
Noticed a log message that was printing out raw `%s`.
Added in the (presumably) intended template arguments.
=> Fix log with un-templated parameters

rq/__init__.py
Added `SpawnWorker` to what `__init__.py` exposes, otherwise code like this won't work:
```python
from rq import SpawnWorker, Queue
````
------
I tried to start using `SpawnWorker` after installing HEAD from Git[0] but was getting ImportError[1] until I added `SpawnWorker` to `__all__`. This commit+PR resolves that issue.
- [0] - `pip install -U "git+https://github.com/rq/rq.git@97f1a4190a4b61e004b16ba8211baaac9eae2de7#egg=rq"`
- [1] `ImportError: cannot import name 'SpawnWorker' from 'rq' (/home/user/projects/victorb/actions/.venv/lib/python3.10/site-packages/rq/__init__.py)`
=> Add `SpawnWorker` to `__init__.py`

.pre-commit-config.yaml, pyproject.toml, rq/registry.py, tests/test_registry.py
[Mentioned here](https://github.com/rq/rq/pull/2180#issuecomment-2696048019) there's one more timezone-naive timestamp conversion. This fixes it. 
Also updated the pre-commit versions of ruff, pyproject-fmt, and added simple pre-commit-hooks.
`pyproject.yaml` changes:
* Most formatting comes from the `pyproject-fmt`
* Added dev dependency group so `uv sync` installs everything for local development.
=> Remove timezone naive coversion

.github/workflows/codeql.yaml, .github/workflows/dependencies.yml, .github/workflows/docker.yml, .github/workflows/lint.yml, .github/workflows/workflow.yml, README.md, rq/utils.py
Updated deprecated `run-os` to `ubuntu-latest`
Changed the [codecov deprecated](https://github.com/codecov/codecov-action?tab=readme-ov-file#migration-guide) `file` to `files.
=> Update deprecated action runners

rq/executions.py, rq/job.py, rq/queue.py, rq/registry.py, rq/utils.py, rq/worker.py, tests/test_executions.py, tests/test_intermediate_queue.py, tests/test_job.py, tests/test_registry.py, tests/test_scheduler.py, tests/test_worker.py
* Added `parse_job_id` method. BaseRegistry would return the id as_text, but StartedJobRegistry would parse the job_id from `job_id:execution` format.
* StartedJobRegistry.cleanup() now properly saves the job result into job result (using the _handle_failure)
* Added an option for the `Queue.enqueue_dependents` to prevent refreshing the job status, if the job status has been updated in the pipeline)
* Added deprecation notices to avoid adding/removing a job to the StartedJobRegistry (only Executions are allowed)
* Added a test where the job that is still executing would not be cleaned up, while in the started queue (test_no_cleanup_while_in_started_queue)
* Updated tests to exercise the StartedJobRegistry separately from the BaseRegistry.
* Added tests for a few warnings
=> Update the StartedJobRegistry to use correct job_id extracting

rq/queue.py, tests/test_queue.py
This PR enhances the handling of Redis pipelines within the `setup_dependencies` method in `rq/queue.py`. 
Specifically, it addresses the scenario where jobs without dependencies are enqueued using a shared Redis pipeline across multiple queues. Previously, the pipeline's multi() method was called unconditionally, which prevented enqueuing multiple jobs across different queues using the same pipeline.
This PR will resolve #2211.
=> Fix duplicate multi() on the same pipeline

rq/worker.py
Fixes #2220
Socket timeout could be set by users or overridden by some library, in this case background pubsub thread exits and doesn't recover. 
Caused by my previous change: https://github.com/rq/rq/commit/3829df7cfef59ba0a49d7f0acf2b9236358b770d 
This change was required to avoid rapid polling and can be fixed by just increasing timeout to 60s instead of previous 0.2 seconds.
=> fix: Add Timeout in PubSub thread

rq/cli/workers.py, rq/job.py, rq/queue.py, rq/registry.py, rq/serializers.py, rq/worker.py, rq/worker_pool.py, tests/__init__.py, tests/test_commands.py
There are two main changes here.
1. Even though several serializer variables are annotated as `Type[Serializer]`, as far as I can see, a serializer is not actually required to be a type. Change such annotations to just `Serializer` and update the `Serializer` protocol to a conventional protocol with methods.
2. Since RQ now requires Python 3.8, it can make use of `runtime_checkable`. Do that to simplify the serializer interface check.
In addition, add some more type annotations to serializer-type variables.
=> Improve the typing of serializers

tests/__init__.py, tests/test_cli.py, tests/test_intermediate_queue.py, tests/test_job.py, tests/test_queue.py, tests/test_results.py, tests/test_worker.py, tests/test_worker_pool.py
I have found that relying on garbage collection for cleaning up Redis connections can result in deadlocks. `Redis.close` acquires a lock, so if GC runs while that lock is already acquired, it will deadlock.
In #2249, I've added _some_ deterministic cleanup, but since then I observed these deadlocks happening again. So I went through all other instances of Redis connections being created, and added deterministic cleanup for all of them. Hopefully, this fixes the problem for good.
Note that `TestCase` appears to be a duplicate of `RQTestCase`, so I just deleted it instead of adding cleanup. I also fixed a couple of minor problems in `RQTestCase`.
=> tests: clean up Redis connections deterministically

rq/group.py, tests/test_group.py
https://github.com/rq/rq/issues/2269
* Use a fresh pipeline for each call to `cleanup()`
* Should avoid the case where `job_ids` and `results` have different lengths
* Return early if no jobs are found
=> Avoid IndexError during group cleanup

docs/css/screen.css
fixes #2206
Let me know if it could be improved somehow
Before:
After:
=> Improved table formatting
