.gitignore
docs/index.md

For #463
While I was in there I added some stuff for the other `.enqueue()` arguments, I don't actually know if these are right so please correct me if not.

docs for new at_front enqueue argument

---

README.md

"An" should be used here because "RQ" sounds like "ar-kiu".
https://www.englishclub.com/pronunciation/a-an.htm

Tiny fix of the indefinite article before "RQ"

---

rq/queue.py

See https://github.com/nvie/rq/issues/472#issuecomment-74859743 for explanation.

lrem only first occurrence of the job id (we expect only one)

---

rq/cli/cli.py
rq/cli/helpers.py
tests/test_helpers.py

This PR allows user to specify connection params via config file

Restored the ability to specify connection params in config

---

docs/workers.md

Doing a little to say thanks for a great piece of software.

docs: add missing 'to' fixes #433

---

rq/queue.py

ZADD bugfix

---

rq/registry.py
tests/test_registry.py

Fixes #509 . If there's no complaints about this PR, I will merge this in a few days.

Jobs from FinishedJobRegistry should have "failed" as status when moved to FailedQueue

---

rq/queue.py
rq/worker.py
tests/test_worker.py

This is a fix to: https://github.com/nvie/rq/issues/255
Now all of these will work.
```python
w = Worker('high')  
q = Queue(name = 'high')
w = Worker(q)
queue_names = ['high', 'normal', 'default']
w = Worker(queue_names)
w = Worker((map(Queue, queue_names))
w = Worker((list(map(Queue, queue_names)))
w = Worker([queue_names, q])
```
This is my first ever attempt at contributing to an open source project. All feedback is greatly appreciated.

updated worker api see issue 255

---

README.md

* Added docs link at the top of the page, much easier to see.
* Changed docs link to github pages

Fixed docs links

---

rq/queue.py

make args and kwargs explicit for enqueue_call function

---

rq/worker.py

Ensure custom exception handlers call when Redis is down

---

docs/jobs.md

Added documentation for failed queue

---

rq/worker.py

log.info added when cleaning registries

---

.gitignore
rq/registry.py
tests/test_cli.py
tests/test_connection.py
tests/test_job.py
tests/test_queue.py
tests/test_registry.py
tests/test_sentry.py
tests/test_worker.py

Was planning to add scheduled task feature, until I found [this repo](https://github.com/ui/rq-scheduler) ... 
So only some depreciation fixes :)

depreciation fixes

---

rq/job.py
rq/worker.py

`hget` will return bytes value in python3.
make sure state is text type and json serialisation-able.
https://github.com/nvie/rq-dashboard/pull/90 same problem

make sure state and exc_info is text_type

---

rq/worker.py
tests/test_worker.py

I am sorry for the double PR. I'm new to creating PRs. The previous one was based off of the wrong branch. Sorry for the noise.
Original message
Trying to add the asked for test case in #558. I am new to unit testing so it might be that I have not chosen the correct position for it.
@grzaks I hope you don't mind and thanks for the original PR.

worker left with current_job set after job exception

---

README.md

* Use explicit connection management instead of `use_connection()`.
* Use `rq worker` instead of `rqworker`.

Update outdated sample codes in README.md

---

rq/worker.py
tests/test_worker.py

Would you be interested in something like this? I use it on a custom UI to tell the user that he already clicked on the "delete after job finishes" button.

Save date on which a busy worker receives a warm shutdown request

---

tests/test_queue.py
tests/test_worker.py

Somes minor fixes and adding a few tests.

Test fixes

---

rq/worker.py

Update job status with set_status instead of setting attribute
PR for #658

Update job status with set_status

---

docs/workers.md

Documentation for https://github.com/nvie/rq/pull/657.

Add documentation for custom queue and job classes

---

rq/worker.py

Thanks to @rebeckag for reporting the issue #696

worker.py: Fix default logging_level

---

rq/exceptions.py
rq/worker.py
tests/fixtures.py
tests/test_worker.py

adding heroku worker

---

rq/queue.py
tests/test_queue.py

fetch_job: queue correct queue

---

rq/queue.py

Apply's @mattseh's fix for https://github.com/nvie/rq/issues/753.

Pass pipeline to push_job_id from enqueue_job

---

docs/index.md
docs/testing.md
patterns/index.md

[DOCS] Fix and complete examples with `async` + HerokuWorker

---

rq/worker.py
tests/test_worker.py

as per @Chronial's comment on b4b99f3

correct heroku worker exit logic

---

rq/worker.py
tests/test_worker.py

Worker `handle_exception` and `move_to_failed_queue` couldn't handle a situation where the exception raised had non-ascii characters. This caused a UnicodeDecodeError when trying to format the exception strings.
Ensured strings get decoded before building the exception string.
Closes #482

Fix UnicodeDecodeError when failing jobs

---

rq/compat/__init__.py
tests/fixtures.py
tests/test_worker.py

Solve the UnicodeDecodeError while decode literal things.

---

rq/worker.py

For easier debugging of unexpected exits of workhorses.

Add waitpid() return value to workhorse error/log messages

---

rq/job.py
tests/test_job.py

introduce job.update_meta() to store updated meta to Redis

---

docs/jobs.md

Add documentation for job.save_meta()

---

rq/queue.py
rq/utils.py

* Added support to use strings to specify both result_ttl and ttl.
* Added Days as possible timeout string (as 'd')

Expand timeout string feature to both result_ttl and ttl, and add days possibility.

---

rq/job.py

job.refresh has been call in job.fetch

Optimize job.dependency

---

rq/utils.py
tests/helpers.py
tests/test_job.py
tests/test_utils.py
tests/test_worker.py

add milliseconds into timestamps

---

rq/decorators.py

There is already a Pull request for this option, but it hanged up a year ago (#752).

Add at_front option for decorated functions

---

rq/queue.py
tests/test_queue.py

Fixed #731 - Support for deleting Queues

---

rq/suspension.py
rq/worker.py

Added heartbeat in `is_suspended`

Fixed #812 - Send heartbeat during suspension check

---

docs/workers.md

Just 2 lines about using the sentry.io service.

Added note about rq and raven

---

docs/docs/index.md

Fixes issue #934 - Documented Queue.delete

---

tests/test_worker.py

skip test_1_sec_shutdown with pypy

---

run_tests
tox.ini

Update run_tests script to use pytest instead of unittest.
Update tox.ini envlist.

Fix run_tests to use pytest.

---

rq/queue.py
tests/test_queue.py

Fix #1040 and add tests for queue default_timeout.

Fix #1040 queue default timeout bug.

---

docs/docs/index.md
docs/docs/jobs.md
docs/docs/results.md
docs/docs/workers.md

Having the same titles on all my tabs is making me crazy. Hopefully this will fix it!

Give better titles to documentation pages

---

docs/docs/index.md

Update index.md to add "import time"

---

rq/worker.py

`exc_string` is formatted in next line.

remove unused code

---

rq/worker.py

Replace procname with setproctitle

---

docs/docs/workers.md
rq/worker.py

Update worker document for setproctitle feature

---

docs/docs/jobs.md

Edits to the "jobs" page of the documentation to make things clearer for new users. In particular, when I first read the docs I saw a job is retrieved using the job id. But it wasn't immediately clear just from this page where one gets the job id. The page seemed to suggest using get_current_job(), but in fact that only works from within the job function.
Some of this does duplicate information from index.md in the interest of lessening the amount of jumping from page to page needed to get the concepts.

Edit jobs doc for clarity

---

rq/registry.py
tests/test_registry.py

Fixes https://github.com/rq/rq/issues/1143

Failed jobs will now auto expire

---

rq/job.py
rq/queue.py
tests/test_job.py
tests/test_scheduler.py

Update tests for this change
Closes: #1179

Add job status setting in enqueue_at (and in enqueue_in) methods

---

rq/worker.py

Fix simple typo: constrast -> contrast

---

rq/worker.py

fix kill_horse will cause zombie processes

---

.deepsource.toml
MANIFEST.in
rq/cli/helpers.py
rq/scheduler.py

- Use literal syntax to create the data structure
- Remove unnecessary comprehension
---
Find the other issues found here - [https://deepsource.io/gh/pnijhara/rq/issues/?category=all](https://deepsource.io/gh/pnijhara/rq/issues/?category=all)
This PR also adds `.deepsource.toml` configuration file to run DeepSource analysis on the repo with. Upon enabling DeepSource, the analysis will run on every PR and commit to detect 560+ types of issues in the changes — including bug risks, anti-patterns, security vulnerabilities, etc.
To enable DeepSource analysis after merging this PR, please follow these steps:
1. [Signup](https://deepsource.io/signup/) on DeepSource with your GitHub account and grant access to this repo.
2. Activate analysis on this repo [here](http://deepsource.io/gh/rq/rq).
You …

Fix some code quality issues

---

rq/job.py
rq/queue.py
rq/worker.py
tests/test_job.py
tests/test_queue.py

Continuing the last bit of work from @thomasmatecki 's PR https://github.com/rq/rq/pull/1170

Multi dependencies

---

docs/docs/jobs.md
rq/job.py
rq/queue.py
tests/test_job.py
tests/test_queue.py

Fix #1197
Signed-off-by: Paul Spooren <mail@aparcar.org>

Add get_job_position and get_position feature

---

README.md

It might be beneficial to add the link to such dashboards in readme for easy accessibilty.

updated readme with link to monitoring dashboards

---

.github/workflows/test.yml
rq/registry.py
rq/scheduler.py
rq/worker.py

Fix https://github.com/rq/rq/issues/1264

Fix scheduler on Python 3.8

---

rq/worker.py
tests/test_worker.py

Split kill_house() fix issues #1234

---

rq/scheduler.py

I noticed that logs for the scheduler did not have a logger name (they currently use "root"), so I created a logger instance with the proper name. The heartbeat logs are also pretty spammy, so I switched them to level == DEBUG. 
```
worker_1               | {"message": "Scheduler sending heartbeat to default", "time": "2020-07-30T19:43:55.214250", "level": 20, "status": "INFO", "logger": {"name": "root"}}
worker_1               | {"message": "Scheduler sending heartbeat to default", "time": "2020-07-30T19:43:56.222468", "level": 20, "status": "INFO", "logger": {"name": "root"}}
worker_1               | {"message": "Scheduler sending heartbeat to default", "time": "2020-07-30T19:43:57.226420", "level": 20, "status": "INFO", "logger": {"name": "root"}}
worker_1               | {"message": …
```

Use correct logger name for scheduler and lower level for heartbeat logs

---

MANIFEST.in

include requirements.txt in sdist

---

rq/worker.py
tests/test_worker.py

Fixes https://github.com/rq/rq/issues/1333

Fixes an issue where retried jobs should not be put in FailedJobRegistry

---

rq/queue.py
tests/test_scheduler.py

Fix for https://github.com/rq/rq/issues/1338

pass retry param to enqueue_at func

---

Dockerfile
dev-requirements.txt
run_tests_in_docker.sh

useful to run full test suit on Mac

tests: added ability to run tests in Docker

---

rq/scheduler.py
rq/worker.py

Closes #1365 
I can confirm that I get the expected (lack of) output when running in quiet mode.

Propagate logging settings from worker to scheduler

---

docs/docs/jobs.md

Took me a while to figure out I needed to do `job.refresh()` in my code. Probably worth adding to the main docs.

Add `job.refresh()` to docs

---

rq/scheduler.py

As I've reported in #1398, an exception was raised when I tried to run a worker with enabled scheduler in combination with a Redis server that the client connects to via UNIX domain socket.
I believe this change fixes the issue, and it works in my setup.
The approach I used is basically the same as the one already used in case an `SSLConnection` is in the pool.

Fix scheduler when UNIX socket path is configured

---

rq/job.py
tests/fixtures.py
tests/test_job.py

Example:
```
async def run(arg1):
[some code]
q = Queue(connection=Redis())
job = q.enqueue(run, arg1=arg1)
```

Add runner for asyncio tasks

---

docs/docs/jobs.md
rq/command.py
rq/job.py
rq/worker.py
tests/test_commands.py

Add a "stopped" JobStatus and the machinery to properly handle it

---

docker/Dockerfile

PR of #1448 
For more information please read #1448.

Changed docker CMD to ENTRYPOINT

---

rq/job.py
rq/registry.py
rq/worker.py
tests/test_job.py
tests/test_registry.py
tests/test_retry.py
tests/test_worker.py

Fixes https://github.com/rq/rq/issues/1461

Jobs that get cleaned up should also be retried

---

rq/cli/helpers.py
tests/test_cli.py

Use same variable names as in config file.
fix #1342

Add environment variables for connection

---

docs/_config.yml
docs/_layouts/chat.html
docs/chat/index.md
docs/chat/join.html

Added discord for RQ and a page of the website to join.
closes #865

Add chat page

---

.github/workflows/docker.yml

I forgot to change this in #1471 by mistake.

Quickfix: Change Dockerhub Username

---

docs/docs/jobs.md

Docs: Add scheduled to job.get_status()

---

rq/queue.py
tests/test_queue.py

Resolves #1497
The added unit test shows an example that would have failed prior to this change.

Ensure pipeline in multi mode after dep setup

---

.github/workflows/dependencies.yml
tests/test_cli.py

You can read more in https://github.com/rq/rq/pull/1465#issuecomment-842464560.
Sorry for these many commist, what sometimes only include logs, but I can't test something like this localy.

Daily workflow for dependency testing

---

.github/workflows/dependencies.yml

fix query request of issue listing

Fix Dependencies

---

tests/test_registry.py
tests/test_retry.py

Closes #1522
See also: [Test rq #307](https://github.com/rq/rq/runs/3022835044?check_suite_focus=true#step:7:34), [Test rq #319](https://github.com/rq/rq/runs/3103741767?check_suite_focus=true#step:7:34)

Make unstable tests more stable

---

README.md

Python-rq is the great package...congrants!
Just fixed the typo issue in the readme file in a method enqueue_in(). Changed 8 to 10 , corresponding to the date >>> 10th of October
Its a minor change, but may consider to merge my PR
Thanks

fix: typo on readme file - enqueue_in()

---

rq/queue.py

Fixes https://github.com/rq/rq/issues/1518

add None check before dependencies_are_met

---

rq/registry.py
tests/test_cli.py
tests/test_registry.py

Fixes https://github.com/rq/rq/issues/1542

Requeueing job should clear job.exc_info

---

rq/scheduler.py
tests/test_cli.py
tests/test_scheduler.py

Fixes https://github.com/rq/rq/issues/1531

Add more tolerance to scheduler heartbeat

---

rq/queue.py
rq/registry.py
tests/test_queue.py
tests/test_registry.py

Add missing functionality for CanceledJobRegistry

---

rq/job.py
rq/registry.py

This allows people to specify if they want a requeue to place at the front (which at_front already has support).

Support at_front requeue support

---

rq/job.py
rq/queue.py
tests/test_dependencies.py
tests/test_job.py

Fixes https://github.com/rq/rq/issues/1691

Job should not be enqueued if dependency is canceled

---

rq/worker.py

Hi,
My remote redis provider doesn't seem to provide all of the `CLIENT` commands. Because of that, I am sending a quick fix, since I don't want to update everytime a new version you guys release :)
Love the product btw. Thanks!

fix listindex error

---

rq/scheduler.py

scheduler heartbeat for acquired locks only

---

docs/docs/index.md
rq/job.py
rq/queue.py
tests/test_dependencies.py

Add feature to enqueue dependents at the front of queues

---

rq/worker.py

Should fix https://github.com/rq/rq/issues/1706

Fix broken pipeline / transaction

---

docs/css/screen.css

- html font size removed, body font size set in rem w/o weight for better readability 
- font stacks with system fonts defined - Lato font wasn't even imported, so it wouldn't load for most users
- code formatted w/ prettier rules

#1733 Typography adjustments for docs

---

rq/scheduler.py

closes https://github.com/rq/rq/issues/1717

Move lock aquire log from INFO to DEBUG level

---

rq/queue.py
rq/scheduler.py
tests/test_scheduler.py

as per @selwin's request, I'm submitting this small PR to add at_front capabilities to scheduled jobs. This is my first PR to an open-source project, so any guidance would be really appreciated. (Will have similar PR for RQ-Scheduler)

Add at_front for scheduled/enqueue_at jobs

---

rq/registry.py

Fix Scheduler Docstring

---

rq/command.py
rq/connections.py
rq/job.py
rq/logutils.py
rq/queue.py
rq/registry.py
rq/results.py
rq/scheduler.py
rq/suspension.py
rq/timeouts.py
rq/utils.py
rq/worker.py
rq/worker_registration.py

Adds more docstrings to a few modules.

Queue Docstrings

---

.github/workflows/lint.yml
README.md
rq/__init__.py
rq/cli/cli.py
rq/cli/helpers.py
rq/command.py
rq/connections.py
rq/contrib/sentry.py
rq/decorators.py
rq/defaults.py
rq/job.py
rq/local.py
rq/logutils.py
rq/queue.py
rq/registry.py
rq/results.py
rq/scheduler.py
rq/serializers.py
rq/timeouts.py
rq/utils.py
rq/worker.py

This PR applied the black code style, adds it to the CI and README. The changes look big, however no functional changed are applied at all.
The line length is set to [120](https://github.com/rq/rq/pull/1290#discussion_r449855514), which is different from black recommendation of [88](https://github.com/psf/black#command-line-options). I would suggest to stick to the 88 recommendation and adapt the `flake8` check.

Black style

---

rq/queue.py
rq/worker.py

Current worker on debug mode doesn't raises errors, but does have some formatting issues.

Debug mode log fixes

---

rq/job.py
rq/queue.py
rq/worker.py
rq/worker_registration.py
tests/test_job.py
tests/test_results.py

Fixes https://github.com/rq/rq/issues/1792

Sync jobs should save job exceptions and results

---

rq/queue.py
rq/scheduler.py
tests/test_scheduler.py

Add to worker redis record scheduler info

---

docs/contrib/testing.md

@selwin the last one should've been a draft, I hadn't reviewed it properly, sorry.
Fixed some typos here.

docs: fix typos

---

docs/patterns/index.md

fixed minor duplicate article ("the its config var")

Updated index.md

---

rq/queue.py
rq/scheduler.py
rq/worker.py

Remove unsafe formatting and use builtin logging parameters instead.

fix: remove unsafe formating and standardize qoutes

---

rq/job.py
rq/queue.py
rq/registry.py
rq/scheduler.py
tests/test_dependencies.py

Check dependencies when enqueue via Queue.enqueue_job()

---

rq/connections.py

Help when grepping through warnings.

Fix typo in deprecation warning

---

rq/cli/cli.py
rq/cli/helpers.py

Moved some stuff to `helpers.py`

Cleaned up cli.py

---

rq/queue.py

Prior to this, the debug line would dump the pipeline `__repr__` into the string instead of the number of jobs on the queue.
Example:
```
DEBUG 2023-04-25 18:17:40,497 queue Pushed job c6027356-9ac4-4228-bae9-3e057543ca18 into default, Pipeline<ConnectionPool<Connection<host=redis,port=6379,db=2>>> job(s) are in queue.
```

Update `push_job_id` debug string when using pipelines

---

tests/test_callbacks.py

Fix linting error introduced in https://github.com/rq/rq/commit/192fbc9c507bb5f3347f39304b5c2fb8ea8f7f43

[Linting] Fix linting error

---

rq/job.py

This PR improves observability of job workflows. 
It is quite painful to easily figure whether a job has been retried or is done retrying, after a failure. Currently not possible via looking at logs. The PR helps with that by logging when the job has been enqueued/scheduled as part of a retry, and with how many retries left.
Hope this helps!

Add logging for job retries

---

rq/worker.py
rq/worker_pool.py
tests/test_worker_pool.py

Set workerpool with_scheduler defaults to True

---

rq/cli/helpers.py

Add support for `REDIS_SSL_KEYFILE` and `REDIS_SSL_CERTFILE` configuration

Extend ssl config options

---

rq/job.py
tests/test_job.py

Adds validation to avoid ":" when user pass job_id

---

rq/command.py
rq/decorators.py
rq/group.py
rq/job.py
rq/local.py
rq/logutils.py
rq/queue.py
rq/suspension.py
rq/timeouts.py
rq/utils.py
rq/worker.py

This PR fixes various spelling errors across the RQ codebase to improve code quality and documentation clarity.
Corrections across 11 files:
- **command.py**:
- Fixed 'availble' → 'available'
- Fixed 'Kiling' → 'Killing'
- **job.py**:
- Fixed 'dependecy' → 'dependency'
- Fixed 'sucessfully' → 'successfully'
- Fixed multiple docstring typos
- **queue.py**:
- Fixed 'THe' → 'The'
- Fixed 'referce' → 'reference'
- **worker.py**:
- Fixed 'Instanciates' → 'Instantiates'
- Fixed 'workig' → 'working'
- Fixed 'adresses' → 'addresses'
- **decorators.py**: Fixed 'Arbitraty' → 'Arbitrary', 'Failture' → 'Failure'
- **group.py**: Fixed 'Groupes' → 'Groups'
- **local.py**: Fixed 'instanciated' → 'instantiated'
- **logutils.py**: Fixed 'looger' → 'logger'
- **suspension.py**: Fixed 'suspendeed' → …

Fix spelling errors across RQ codebase

---

.github/workflows/workflow.yml
docs/docs/workers.md
rq/job.py
rq/worker.py
tests/test_spawn_worker.py
tests/test_worker.py

Fixes https://github.com/rq/rq/issues/2058

Added SpawnWorker

---

rq/job.py

Fix missing variables from retry log

---

examples/run_example.py
examples/run_worker.py

Failing since 67624eba0b09 (#2043)
with the following error:
```python
Traceback (most recent call last):
File "/tmp/rq/examples/run_example.py", line 6, in <module>
from rq import Connection, Queue
ImportError: cannot import name 'Connection' from 'rq' (/tmp/rq/rq/__init__.py). Did you mean: 'connections'?
```

Fix example

---

examples/run_example.py
examples/run_worker.py

- **Fix forgotten parenthesis**
- **Unnecesary run_worker.py**
- **use the same convetion as in documentation**
- **more precise name for `jobs`**
- **Precise with job.get_status()**
- **don't refresh to maintain consistency**
- **convert jobs from dict to list**
- **Split main() in 2 smaller functions**
Please see git messages for rationale.
The important commit is *Fix forgotten parenthesis*, the rest are a refactor.

fix example V2

---

docs/docs/results.md

- **no return means function/task returns None**
- **Remove incorrect paragraph**
Related to https://github.com/rq/rq/issues/2216

docs: remove paragraph

---

examples/run_example.py

- **example: revert "refresh=False"**
- **refactor get status**
Fixing an error I introduced in https://github.com/rq/rq/pull/2212/commits/43ea3d901a23de7a1e9c5acdb7f09136046fd2a7

example: refresh=True

---

rq/worker.py

Fix https://github.com/rq/rq/issues/2222

Don't try to import SIGRTMIN in worker.py

---

rq/worker.py
tests/test_worker.py

Hide job description on success. This can be used to hide sensitive information.

Hide job description on success

---

rq/worker_pool.py

Hi. Sorry for my English. If I use a custom worker class and it has a custom queue class, i get the exception https://github.com/rq/rq/blob/master/rq/worker.py#L483. Is there a reason why this is impossible?

Using a queue class from a classvar Worker in WorkerPool

---

rq/worker.py
tests/test_worker.py

Fixed a regression in Worker.__init__

---

rq/worker.py
tests/test_spawn_worker.py

Fixes https://github.com/rq/rq/issues/2290

SpawnWorker should reconstruct Execution object
